### ISSUE TITLE
How to get coordinates (in geoJSON) of the route calculated using mapbox-directions.js plugin?

### ISSUE THREAD

**Issue by cesaregerbino** [mapbox/mapbox-sdk-js#108]
I'm using MapBox Directions JS plugin following this sample

    https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/

I need to obtain the route coordinates, in GeoJSON format.

Any suggestions / example / links?

Thank you in advance!!!

Cesare

**Comment by lyzidiamond** [comment]
Hi Cesare,

This is not the correct repo for this request. I will point you in the right direction for now, but in the future please route these questions through our contact form at https://www.mapbox.com/contact.

To make requests directly to the Mapbox Directions API and get route coordinates as a response, see the documentation: https://www.mapbox.com/api-documentation/#directions.
