### ISSUE TITLE
Internal Promises are swallowing errors in callbacks

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-sdk-js#109]
Given this mistake in a Node script:

``` js
client.listDatasets((err, datasets) => {
  undefinedThing();
});
```

What I see is this unhelpful message:

```
Potentially unhandled rejection [2] undefined (WARNING: non-Error used)
```

That suggests to me that internal Promises in this library are swallowing errors thrown in callbacks.

**Comment by davidtheclark** [comment]
I tried to look into this but I'm some trouble figuring out how to address the problem. 

I *think* the issue could be that the `rest` library deals in Promises, such that [the interceptor we use to call the callback](https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/callbackify.js) runs *within a Promise*, so if the calling of the callback throws any errors, those are swallowed up — and yet the user has no way to *see* them. We could try to modify the code some to wrapped the call in try-catch and then call the callback a second time with an error that resulted from its first call — but that's very mirror-hall-y, not a good idea.

If this hunch is right, and the problem is that `rest` deals in Promises while this library tries to deal in callbacks, *I don't know any way out of this conundrum without converting this library to Promises.* Does anybody else see a way?

cc @scothis

**Comment by scothis** [comment]
What's happening is that the callback is throwing an error and the [callbackify interceptor](https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/callbackify.js) isn't handling that error which cases the thrown value to enter the promise chain as a rejected value. The rejected promises is unhandled because there is no error handler for promise returned by `client.listDatasets`

**Comment by davidtheclark** [comment]
@scothis But _can_ the callbackify interceptor handle the error in such a way that it gets *thrown*, as you'd expect from a callback API?

**Comment by scothis** [comment]
Not really, there's nobody to catch the thrown value. Unless you're looking for node to crash. The best thing to do is for the callbackify interceptor to catch the error and log it.

**Comment by davidtheclark** [comment]
> The best thing to do is for the callbackify interceptor to catch the error and log it.

Well, I can submit a PR for that. Seems like an interim, less-than-ideal solution. What about switching the library to being Promise-based instead of callback-based? That seems like the logical endgame.

If I understand https://github.com/mapbox/mapbox-sdk-js/pull/77, it should mean that the user can currently use a callback *or* a Promise? Is the idea to fade out the callback — if so, when? And why isn't the Promise API documented?

**Comment by scothis** [comment]
> What about switching the library to being Promise-based instead of callback-based? That seems like the logical endgame.

It already is, each method should return a promise. You can skip passing in a callback function.

**Comment by davidtheclark** [comment]
Yes ... so what about phasing out callbacks, since they have this kind of fundamental problem, and documenting Promises as the API?

**Comment by scothis** [comment]
Fine by me. @tmcw ?

**Comment by davidtheclark** [comment]
This should be fixed by the newly published @mapbox/mapbox-sdk.
