### ISSUE TITLE
geocodeForward does not seem to take proximity into account

### ISSUE THREAD

**Issue by danholten** [mapbox/mapbox-sdk-js#110]
Hi all,

I tried the mapbox JS SDK and wanted to get more relevant query results by passing a proximity object along. The case below is an example of how proximity objects do not seem to be taken into account from a semantic point of view (at least as far as I can tell) by the API. I checked the network request, i.e., the actual API call, as well and the proximity parameter is correctly passed along, but api.mapbox.com doesn't seem to be doing anything with it based on the returned relevance score for the features).

1). search for 'Paris' (only return places) in the vicinity of **Cannes, France** (lat/lon = 43.552849, 7.017369):

`mapBox.geocodeForward('Paris', { proximity: { latitude: 43.552849, longitude: 7.017369 }, types: 'place' })`

Network request (generated by the SDK):

`https://api.mapbox.com/geocoding/v5/mapbox.places/Paris.json?proximity=7.017%2C43.553&types=place&access_token=xxx`

Result (only showing the first two features in the array (in return order) and only showing the 'id', 'place_name', 'relevance', and 'center' properties of each feature):

`[
{"id":"place.3822546929459038","place_name":"Paris, Paris, France","relevance":0.99,"center":[2.3417,48.8592]},
{"id":"place.8966099946497330","place_name":"Paris, Texas, United States","relevance":0.99,"center":[-95.5555,33.6618]}
]`

Given the 'proximity' query parameter that is passed along with the URL and given the 'center' properties of the returned results, it is clear that 'Paris, Paris, France' should have a higher 'relevance'-property value than 'Paris, Texas, United States', but this is not the case. The next example searches in the vicinity of Texas and returns exactly the same result, although in that case 'Paris, Texas, United States' should have a higher 'relevance'-property score.

2). search for 'Paris' in the vicinity of **Houston, Texas** (lat/lon = 29.682720, -95.593239):

`mapBox.geocodeForward('Paris', { proximity: { latitude: 29.682720, longitude: -95.593239 }, types: 'place' })`

Network request (again generated by the SDK, nothing manual):

`https://api.mapbox.com/geocoding/v5/mapbox.places/Paris.json?proximity=-95.593%2C29.683&types=place&access_token=xxx`

Result:

`[
{"id":"place.3822546929459038","place_name":"Paris, Paris, France","relevance":0.99,"center":[2.3417,48.8592]},
{"id":"place.8966099946497330","place_name":"Paris, Texas, United States","relevance":0.99,"center":[-95.5555,33.6618]}
]`

The result (most notably the order of features in the result array and the relevance score for each feature) is the same again (both results are actually _completely_ the same).

Any idea what's going on here (or what I'm doing wrong?)

Thanks in advance, Danny.

**Comment by mattficke** [comment]
Hi Danny, thanks for the report. You're not doing anything wrong, proximity biasing just has a limited effect for larger features like cities. We're working on improving that right now, but at the moment it works best for small features like addresses, and only when the proximity point is within 5-10 miles of the feature.

To answer your question about relevance, that value is not affected by proximity bias. It's essentially a measure of how closely the query text matches the text of the result. We use an internal scoring system as a tiebreaker to sort features with identical relevances, which is not exposed through the public API, and it's this value that the proximity parameter is biasing.

As I said, we're working to improve the performance of proximity biasing. Until then, if you'd like a more reliable way of filtering non-address features I'd recommend using either the `country` or `bbox` filters: https://www.mapbox.com/api-documentation/#geocoding

Happy geocoding!

**Comment by danholten** [comment]
Thanks a lot Matt, I'll simply order them by distance from the proximity object's lat/lon (on top of the relevance) using some projection transformation, that should do the trick in most cases.
