### ISSUE TITLE
Python? Other languages?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-sdk-js#12]
/cc @dnomadb @sgillies 

Would a similarly-scoped library be useful for Pythonistas? https://github.com/mapbox/node-mapbox/blob/master/API.md

/cc @jfirebaugh what about Rubyists?

**Comment by sgillies** [comment]
@tmcw yeah, I think it would. I've created an issue about uploads at https://github.com/mapbox/api-core/issues/4826 but am happy to move/rescope. I'd definitely like to see the Python lib be something super thin around Requests.

**Comment by dnomadb** [comment]
@tmcw yes, this would be great. I've written and re-written python surface requests so many times for one offs (including some crazy weird stuff we built into the terrain generation process), would be nice to integrate into a better library.

**Comment by tmcw** [comment]
[mapbox-sdk-py](https://github.com/mapbox/mapbox-sdk-py) is alive. Python is the best language to do after node.
