### ISSUE TITLE
List datasets endpoint does not seem to work.

### ISSUE THREAD

**Issue by Joddsson** [mapbox/mapbox-sdk-js#120]
I'm trying to use the "listDatasets" endpoint of the datasets API but I can't get it to work. The response I'm getting is {message: "Not Found"} with HTTP status 404. I'm also using the "listFeatures" endpoint with the same access token, and that works, so I believe there is a problem with the listDatasets endpoint.

I'm working with JavaScript so I'm calling the endpoint as described in the docs. I also tested this with Postman and got the same results.

**Comment by tmcw** [comment]
cc @mcwhittemore - does this error sounds familiar to you?

**Comment by mcwhittemore** [comment]
@Joddsson - the list endpoints only work with tokens that have `dataset:list` access. The available datasets scopes are `read`, `list` and `write`. My guess is your token has `read` access but not `list`.

**Comment by Joddsson** [comment]
Yes! Thank you. 

I created a new access token with dataset:list and now things are working as expected.

**Comment by mcwhittemore** [comment]
@Joddsson good to hear!
