### ISSUE TITLE
how to export dataset to tileset using mapbox api

### ISSUE THREAD

**Issue by Altiano** [mapbox/mapbox-sdk-js#125]
Using the mapbox studio, we have export button, which export the dataset into tileset. 
I want to programatically export to tileset after the dataset has been updated.
The end goal is that the mapbox style can have a up-to-date data.
I can't seem to find how to export to tileset with mapbox-sdk-js

**Comment by andrewharvey** [comment]
https://github.com/mapbox/mapbox-cli-py seems to support this. See https://github.com/mapbox/mapbox-cli-py#datasets-create-tileset

**Comment by Altiano** [comment]
@andrewharvey that's an alternative.. still would be really nice if this is supported here.

**Comment by mmuelder** [comment]
I'm also waiting for a feature like this. Either an "auto-update" feature for tilesets if the underlying dataset has been changed (best solution imho) or a dataset export api call.

Updating datasets via the new API is cool but in many cases useless if the tileset is not updated at the same time.

**Comment by bravecow** [comment]
++ for autoupdate tileset from dataset. Other way tileset are useless for dynamic data 😞 Or i miss something?

**Comment by raquelmsmith** [comment]
Another vote for updating tileset from dataset.

**Comment by joewoodhouse** [comment]
Another vote for this feature.

**Comment by samsammurphy** [comment]
+1 for this feature

**Comment by samsammurphy** [comment]
there appears to be a way to do this in [python](https://github.com/mapbox/mapbox-sdk-py/issues/152) which might apply in [javascript](https://www.mapbox.com/api-documentation/?language=JavaScript#create-an-upload). That is, upload a dataset to a tileset using something like:

```
{
  "tileset": "{username}.mytileset",
  "url": "mapbox://datasets/{username}/{dataset}",
  "name": "example-dataset"
} 
```

**Comment by andrewharvey** [comment]
@samsammurphy that's right. (also mentioned in my comment above). I think a PR implementing this would be most welcome.

**Comment by logan-jobzmall** [comment]
Would love to know the API endpoints to do this as well for cURL

**Comment by davidtheclark** [comment]
With newly published `@mapbox/mapbox-sdk` you can [create an upload with a `mapbox://` dataset URL](https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#createupload).

If you're interested, the HTTP endpoint for accomplishing this is documented here: https://www.mapbox.com/api-documentation/#create-an-upload

I think that's as much as we'll plan to do in the JS SDK. If you're interested in a convenience method without so many steps, I suggest looking at [mapbox-cli-py](https://github.com/mapbox/mapbox-cli-py), which should handle that use case.

Please follow up if you have any questions!
