### ISSUE TITLE
Drop parameter documentation

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-sdk-js#127]
From https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md and link to those sections in https://www.mapbox.com/api-documentation/

c'est cool @tmcw?

**Comment by tmcw** [comment]
I'm not sure we should do this. SDK JS documents javascript types for parameters, whereas api-documentation can only document the HTTP interface, which is entirely strings. So, for instance, the `bbox` parameter looks like `10,1,-10,2` in a URL - is it specified as that string in the sdk, or is it specified as an array of numbers?

**Comment by tristen** [comment]
Is that what the "Show examples in:" JavaScript tab could do for us?

**Comment by tmcw** [comment]
I don't think examples can serve as authoritative documentation - they don't represent the full range of possibilities and even when they do, they leave the question open of whether something else would work.

**Comment by tristen** [comment]
Okie dokie
