### ISSUE TITLE
Geocode batch support

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-sdk-js#13]
The geocode... code should be smart enough to obey Mapbox's special headers in order to geocode big collections of input.

**Comment by sbma44** [comment]
Batch support is currently enterprise-only and also more prone to 500s (if one request is bad...). It also has relatively minor (though real) upside unless requests are made asynchronously. 

:+1: to getting support for batch in the SDK, but it's worth making sure that the user understands the distinction.
