### ISSUE TITLE
Not actual values for profile option of getDirections API method

### ISSUE THREAD

**Issue by zheoreh** [mapbox/mapbox-sdk-js#131]
I have spent many time to find out a reason why getDirections API method became not work for me.
Please fix available values for "profile" option from "mapbox.driving" to "driving" and etc everywhere.
Thanks

**Comment by andrewharvey** [comment]
The API https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/directions.js#L20 needs to decide if `option.profile` expects something in the form `account.profile` or just `profile`.

If `account.profile` it needs to split it up at https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/directions.js#L117.

If just `profile` let's add an `options.account`. I've put forward a PR implementing this approach which feels clearner than splitting `account.profile`.
