### ISSUE TITLE
Tilesets API support

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#133]
:+1: for [Tilesets API](https://www.mapbox.com/api-documentation/#tilesets) support here.

/cc @scothis + a feature request for the Tilesets API to support deletes. I'm not looking forward to manually deleting over 100 tilesets from an account in the Studio UI.

**Comment by lyzidiamond** [comment]
@andrewharvey currently working on adding a delete endpoint to the Tilesets API! In the meantime I can put this task on my list (at least the list endpoint for now).

**Comment by andrewharvey** [comment]
I wanted to test out the tilequery service so I put together https://github.com/mapbox/mapbox-sdk-js/tree/tilequery

**Comment by mattik** [comment]
@lyzidiamond Any update on the delete endpoint in the Tilesets API? 

Would love to have this feature. We also have hundreds of tilesets I need to at some point manually purge..

**Comment by bilics** [comment]
Same here for delete 👍 

Any update on this endpoint support ?

Thanks!

**Comment by paulJordaan** [comment]
+1 for the delete endpoint.

 As far as I know you can only view the last 200 tilesets in Studio (after that you get a warning saying dataset truncated )which makes it impossible to delete tilesets if you have more than 200. Please correct me if I'm wrong
