### ISSUE TITLE
Error: getaddrinfo ENOTFOUND api.mapbox.com api.mapbox.com:443

### ISSUE THREAD

**Issue by przemyslawpluta** [mapbox/mapbox-sdk-js#134]
Hi,

After making a large amount of requests for a longer period of time with `geocodeReverse`

```js
client.geocodeReverse({latitude: at, longitude: long}, (err, res) => {});
```

I'm getting an error that does not recover unless restart of the app.
```
[ Error: getaddrinfo ENOTFOUND api.mapbox.com api.mapbox.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26
```

**Comment by melisoner2006** [comment]
Hi. I'm getting the same error with the geocodeForward function when using mapbox npm module version is 1.0.0-beta7

**Comment by davidtheclark** [comment]
@przemyslawpluta @melisoner2006 Do you think you are encountering rate limiting? https://www.mapbox.com/api-documentation/#geocoding Did you receive response with the status code `429`?

**Comment by davidtheclark** [comment]
Closing as stale. We can re-open if the issue rears its head again.
