### ISSUE TITLE
Add Optimization API

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-sdk-js#135]
https://www.mapbox.com/api-documentation/#optimized-trips

**Comment by davidtheclark** [comment]
@tristen: Looks like Distance API was replaced with the Matrix API: https://github.com/mapbox/mapbox-sdk-js/blob/master/CHANGELOG.md#100-beta8. Should we change this issue title so it's about *adding* the Optimization API?

**Comment by danswick** [comment]
Closed by #257.
