### ISSUE TITLE
support new Static API and rename current as Classic.

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#139]
The current MapboxStatic service is for Static (Classic). I'd like to implement the newer Static service, but not sure what approach to take.

1. Rename the current MapboxStatic service to MapboxStaticClassic and drop in the new Static API into MapboxStatic service.
2. Leave the MapboxStatic service but rename the `getStaticURL` method to `getStaticClassicURL` and drop the new Static API into `getStaticURL`.
3. Drop support for the Static (Classic) API and replace the current implementation to support the new Static API.

All break backwards compatibility though and I'm not sure of a a better solution which doesn't. So what's the preferred approach here?

**Comment by 1ec5** [comment]
In mapbox/MapboxStatic.swift#54, I took advantage of the similarity between both APIs’ overlay options to essentially implement (2) with different map ID/style URL options but identical overlay options.

As far as backwards compatibility, this library is _technically_ pre-1.0 (v1.0.0-beta6 is the latest), so I guess backwards compatibility could be broken with minimal fuss, right?

**Comment by andrewharvey** [comment]
@1ec5 Agreed the identical overlay options makes it easy, I'll tidy up what I've done and PR approach (2).
