### ISSUE TITLE
update upstream documentation

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#142]
The upstream documentation at https://www.mapbox.com/api-documentation/?language=JavaScript#retrieve-a-style still reports Styles API isn't supported in the JS SDK but it is.

**Comment by lyzidiamond** [comment]
@andrewharvey I have a PR open to fix this! I'll post back here when it's reviewed/merged.

**Comment by lyzidiamond** [comment]
I did this! @andrewharvey check it out and, if you feel good about the new docs, go ahead and close this issue ✨

**Comment by andrewharvey** [comment]
Looks good @lyzidiamond !
