### ISSUE TITLE
improve documentation and link to Mapbox API docs

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#146]
- [x] Taking advantage of a newer documentation.js version, API.md can be improved to include a TOC and more complete docs for all services and methods.

- [ ] The README.md should link to [`https://www.mapbox.com/api-documentation/?language=JavaScript`](https://www.mapbox.com/api-documentation/?language=JavaScript) which provides inline mapbox-sdk-js example usage.

/cc @lyzidiamond

**Comment by andrewharvey** [comment]
I've attempted (1) in https://github.com/mapbox/mapbox-sdk-js/commit/d10eed9cfe4b09b62783937725eddbeeaeb8fe2c but it's not working that great yet.

**Comment by itaditya** [comment]
Could you also mention all the api functions in the [doc](https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md) first as a list (on top) so that we can know what functions exist, rather than to scroll all the time

**Comment by andrewharvey** [comment]
> Could you also mention all the api functions in the doc first as a list (on top) so that we can know what functions exist, rather than to scroll all the time

@itaditya That's the intention of the .documentation.yml toc entry at https://github.com/mapbox/mapbox-sdk-js/commit/d10eed9cfe4b09b62783937725eddbeeaeb8fe2c but it needs some more work to fix outstanding issues.

**Comment by mollymerp** [comment]
Thanks for picking this up @andrewharvey! I think a TOC would be awesome, and you're right about linking to the api-docs!! 🙇‍♀️ 
Let me know if you need anything to get your branch ready for review!

**Comment by andrewharvey** [comment]
@mollymerp I don't have much time for this right now, I believe @geografa is working on this at #172. There is an open question about whether it's best to keep both API.md and the [api-documentation](https://www.mapbox.com/api-documentation/?language=JavaScript).

I find API.md is more complete and thorough than api-documentation but lacks the context of the APIs given at api-documentation. I'm leaning towards instead of trying to maintain two sets of docs, we settle on one. GL JS doesn't have an API.md instead using the Mapbox hosted docs, so this repo could do similar. :thinking:
