### ISSUE TITLE
Modularity while expanding to other services

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-sdk-js#15]
As we attempt to bring support for more services into this lib, we'll probably feel the need to break from a single class that defines every one of the methods. Further, there may be advantages to being able to import parts of the library, e.g.

```js
var MapboxDirections = require('mapbox/directions');
```

@tmcw I'm curious what your architectural thoughts are here? It seems to me that `constants.js` and the `MapboxClient` class are basically utilities for any of the services to have access to. Perhaps each service should be a module that instantiates these utilities and then goes on to define the methods pertinent to that service.

**Comment by rclark** [comment]
Just wanted to ask about your motivation behind [using xtend here](https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/client.js#L26-L30). This means all services share a common namespace -- I'd like to think of this is a usability feature, but it may also represent a future bug...

**Comment by tmcw** [comment]
> This means all services share a common namespace -- I'd like to think of this is a usability feature, but it may also represent a future bug

I'm in favor of doing this.

* All services have the same constructor
* Having no object nesting avoids any pecularities with `this` and makes all exports uniform
* Service methods must be service-prefixed: `geocodeForward` rather than `forward`
