### ISSUE TITLE
MapboxStatic service geojson path double encoded

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#154]
In the MapboxStatic service when using a `path.geojson` option, `encode_overlay` will take the GeoJSON object:
```json
{ type: 'Point', coordinates: [0, 0] }
```
JSON.stringify it:
`{"type":"Point","coordinates":[0,0]}`

encodeURIComponent it:
`%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B0%2C0%5D%7D`

Which Is the correct string to return as part of the full static api call, however `uriTemplate` will then do it's own encoding on the `%`char turning it into:
`257B%2522type%2522%253A%2522Point%2522%252C%2522coordinates%2522%253A%255B0%252C0%255D%257D`

...which then fails as at the Mapbox REST API as it is invalid.

The test fixtures are incorrect as they check for the invalid double encoded string.

@scothis I tried to find a way for `uriTemplate` from `rest` to skip the encoding but it doesn't seem possible?

We could leave all the encoding to `uriTemplate` from `rest` by skipping the `encodeURIComponent` step which results in:
`%7B%22type%22:%22Point%22,%22coordinates%22:[0,0]%7D`
This works as a URL in Chrome, but breaks other clients like curl.

**Comment by scothis** [comment]
@andrewharvey yea, the `encodeURIComponent` from https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/encode_overlay.js#L54 certainly appears to be suspicious.

**Comment by scothis** [comment]
Closed via #156
