### ISSUE TITLE
Move URI template constants into services

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-sdk-js#157]
The idea around having the URI template constants be centralized is that it makes refactoring the URL space easier. This hasn't played out in practice, when an API version change does happen, it will still be limited to a single service.

As there is a tight coupling between the template and the code that fills the templated values, the URI templates should be moved from the constants file into the individual services so they are closer to the code they relate to.

**Comment by andrewharvey** [comment]
closed via 5acd36b52ea1fdac35eb2a060794063364f6ada0 #160
