### ISSUE TITLE
Query styles for any account

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-sdk-js#158]
The styles service currently only accepts a style id and assumes the owner for the style is that of the token owner. There are public style, particularly under the mapbox account, that should also be queryable.

Current:
```js
// implicit owner
client.readStyle('cj1g9vgww000k2rr06yemkl64', callback);
```

Proposed:

```js
// implicit owner
client.readStyle('cj1g9vgww000k2rr06yemkl64', callback);
```

```js
// explicit owner
client.readStyle('mapbox', 'cj1g9vgww000k2rr06yemkl64', callback);
```

```js
// style url
client.readStyle('mapbox://styles/mapbox/cj1g9vgww000k2rr06yemkl64', callback);
```

**Comment by davidtheclark** [comment]
The newly published `@mapbox/mapbox-sdk` allows a `ownerId` config option on Styles API service requests.
