### ISSUE TITLE
Geocoding Promise Syntax Inconsistency

### ISSUE THREAD

**Issue by dnlsandiego** [mapbox/mapbox-sdk-js#164]
Using the geocoding promise-based alternative syntax like the example in the README (without passing a options object) throws a `Uncaught Error: options must be an object`.

Is this the expected behavior? The example kind of implies that the options param is optional but reading the source expects one to be passed in when using the promise signature.

I prepared a Webpackbin to replicate the issue:
https://www.webpackbin.com/bins/-KjZU5GvhI1sBWs5NhAL

**Comment by andrewharvey** [comment]
The API doc says for geocodeForward that "options [Object] additional options meant to tune the request (optional, default {})". Since it says here it's optional and defaults to `{}`, if omitting it causes an error that's a bug which should be fixed in my opinion.

**Comment by andrewharvey** [comment]
You're right

https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/geocoding.js#L75
https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/geocoding.js#L197

looks like it's broken for promise syntax. Did you want to submit a PR?

**Comment by dnlsandiego** [comment]
Sure. I'll put together a PR sometime this coming week.

**Comment by joshhendo** [comment]
I've opened a PR here that should fix this: https://github.com/mapbox/mapbox-sdk-js/pull/197

I still need to re-run the tests with a token that has access to more services though.

**Comment by andrewharvey** [comment]
Closed by #197.
