### ISSUE TITLE
a bundled version of library that doesn't require npm

### ISSUE THREAD

**Issue by charliedotau** [mapbox/mapbox-sdk-js#170]
hi there,

Is there - or could there be - a bundled version of the library hosted somewhere that doesn't require npm, for those wanting to pull this straight into our page much like we do the `mapbox gl js` library?

I couldn't see a reference to it in the readme.

Thanks
Charlie

**Comment by andrewharvey** [comment]
:+1: to this being provided at api.mapbox.com like GL JS.

In the meantime you might be able to use a 3rd party service like unpkg.com?

https://unpkg.com/mapbox@1.0.0-beta7/dist/mapbox-sdk.min.js

**Comment by pmyjavec** [comment]
This would be a very welcome addition ! :)

**Comment by stevage** [comment]
Came here to request the same thing. Our GIS team is able to make simple HTML pages with a bit of Javascript, but any kind of build process, plus using NPM would be a significant learning curve.

**Comment by stevage** [comment]
Btw thanks @andrewharvey, that works perfectly.
```
<script src='https://unpkg.com/mapbox@1.0.0-beta7/dist/mapbox-sdk.min.js'></script>
...
var mapboxClient = new MapboxClient(mapboxgl.accessToken);
mapboxClient.geocodeForward('Melbourne Town Hall', function(err, res) { 
  console.log(JSON.stringify(res)); }
);
```

**Comment by answerquest** [comment]
Thanks for this!
Just a note : `mapboxgl.accessToken` isn't some pre-configured thing. You use any variable with the access token string stored in it.
so `var mapboxClient = new MapboxClient(var1);` should work just fine if you've stored your access token in `var1`.

Request : Could we title this thread so that folks who know javascript but don't know about npm and bundling can find this solution?
I'll suggest : "Using mapbox sdk in client-side javascript without any server-side code".

**Comment by answerquest** [comment]
For beginners : [see here](https://github.com/geohacker/bangmandu/issues/4#issuecomment-336085635) for a code example.

**Comment by andrewharvey** [comment]
> Request : Could we title this thread so that folks who know javascript but don't know about npm and bundling can find this solution?
> I'll suggest : "Using mapbox sdk in client-side javascript without any server-side code".

I'd prefer we let Mapbox decide if they will include this library as part of api.mapbox.com or if it'll be left to 3rd parties such as unpkg.com? Then we can simply include instructions for use via the script tag directly in the README around https://github.com/mapbox/mapbox-sdk-js#installation.

**Comment by andrewharvey** [comment]
I've opened #198 aimed to address this issue.
