### ISSUE TITLE
Possibility to pass language when geocoding?

### ISSUE THREAD

**Issue by EnzoEghermanne** [mapbox/mapbox-sdk-js#174]
At https://www.mapbox.com/api-documentation/#request-format, it says that an optional `language` parameter can be passed in to the geocoding service. This appears to be missing in this SDK.

**Comment by EnzoEghermanne** [comment]
I submitted a PR #173 for this.

**Comment by danswick** [comment]
Addressed in https://github.com/mapbox/mapbox-sdk-js/pull/185
