### ISSUE TITLE
document listDatasets fresh option

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#178]
https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md#listdatasets

`opts.fresh boolean whether to request fresh data` but it doesn't explain what is fresh data and what's not. No reference to fresh data at https://www.mapbox.com/api-documentation/#request-format either

**Comment by scothis** [comment]
This property is intentionally not documented because we are not committed to maintaining support for it. In essence a `fresh` requests bypasses caches at the cost of being slower and having a significantly lower rate limit.
