### ISSUE TITLE
finish v1.0.0-beta8 release

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#180]
@geografa did a release in https://github.com/mapbox/mapbox-sdk-js/commit/788248fdb107b5b7fe629e1a62c748a11850c858 however this hasn't been:

- [x] pushed to npm https://www.npmjs.com/package/mapbox
- [x] tagged in git https://github.com/mapbox/mapbox-sdk-js/tags

**Comment by bshyong** [comment]
Would love to see this so it's easier for us to use the Matrix API!

cc @geografa

**Comment by geografa** [comment]
working on this today.

**Comment by bshyong** [comment]
Thanks!

**Comment by geografa** [comment]
@bshyong @andrewharvey added new tags and published this today. I have a failing test that appears to be related to an API change ([new parameter here](https://github.com/mapbox/mapbox-sdk-js/blob/master/test/styles.js#L154)). Could we push this fix for next release?

**Comment by andrewharvey** [comment]
> Could we push this fix for next release?

Yes I think that would make sense as v1.0.0-beta8 is already out the door now.
