### ISSUE TITLE
Reverse Geocoding API documentation Typo

### ISSUE THREAD

**Issue by vikneshwar** [mapbox/mapbox-sdk-js#184]
In Reverse geocoding example, the variable used to create client object is wrong, check [here](https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md#geocodereverse). It should be **MapboxClient** instead of **MapboxGeocoding** but however, it depends upon the variable name you use to **require('mapbox')**. But someone reading the documentation would get confused for a second, so it's better to use the same name throughout the documentation. I can make a PR if so. Thanks !!

**Comment by vikneshwar** [comment]
And another issue with same Reverse Geocoding documentation is `options.types` which is used to filter result to only specific type like address, poi, country...However in the example given it should be enclosed in string as `options: { types: 'address', limit: 3 }`

**Comment by andrewharvey** [comment]
> And another issue with same Reverse Geocoding documentation is options.types which is used to filter result to only specific type like address, poi, country...However, in the example given it is not enclosed in quotes, it should as options: { types: 'address', limit: 3 }

Good spotting, please do submit a PR. (just keep in mind API.md is autogenerated from the source code)
