### ISSUE TITLE
release 1.0.0 so we can get semver back

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-sdk-js#186]
1.0.0-beta7 and 1.0.0-beta8 both featured breaking changes but this hasn't been captured by semver. How about we release 1.0.0, and do away with many beta versions which have been doing bug fixes, new features and breaking changes all together?

**Comment by andrewharvey** [comment]
For the specific case:

https://github.com/mapbox/node-or-tools/blob/master/example/package.json#L8 has

```
"dependencies": {
    "mapbox": "^1.0.0-beta6"
}
```

> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice. However, it presumes that there will not be breaking changes between 0.2.4 and 0.2.5. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.

Unfortuantly these beta increases are assumed by npm to not be breaking, hence installing that node-or-tools example gives mapbox-sdk-js 1.0.0-beta9 (current version), which introduced the breaking change replacing `getDistances` with `getMatrix`

So it seems the easy fix here is to release a new version like 1.1.0 and going forward bump the minor version with any breaking changes.

I'm happy to help out, but I don't think I have the right permissions to do releases on npm, and ideally it would be done by someone at Mapbox.

**Comment by mikemorris** [comment]
Would be much appreciated to get this back onto semver with an actual release.

**Comment by davidtheclark** [comment]
@andrewharvey If you'd like to release v1 with what's there now, I don't see any harm.

The impending revitalization (https://github.com/mapbox/mapbox-sdk-js/issues/211) will involve releasing a new package altogether.

**Comment by andrewharvey** [comment]
In light of #211 I think a v1 release would just be symbolic at this point. Nice to have, but I don't see much actual benefit if there are no new releases or only bug fixes to the `mapbox` package going forward.

**Comment by davidtheclark** [comment]
The `mapbox` package is now deprecated in favor of the newly published `@mapbox/mapbox-sdk`. Versioning will start again. We'll try to hit v1 sooner and more definitively, for sure.
