### ISSUE TITLE
How to export dataset to tileset and create tileset and add tileset to style?

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-sdk-js#189]
The tileset API is the preview, I can't find the API about these questions.

**Comment by andrewharvey** [comment]
Support for dataset to tileset is ticketed at https://github.com/mapbox/mapbox-sdk-js/issues/125. Specifically see https://github.com/mapbox/mapbox-cli-py#datasets-create-tileset on how it's done in the python library.

You could try asking specific how do I questions on https://gis.stackexchange.com/questions/tagged/mapbox

**Comment by davidtheclark** [comment]
Thanks @andrewharvey. Closing as a duplicate of #125.
