### ISSUE TITLE
Browser example

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-sdk-js#19]
This code works great in browsers. This is not immediately obvious. Make it so.

**Comment by rclark** [comment]
I did some experimenting with running client-side tests this morning. The pain points that I ran into:
- node-tap is not browserify-friendly. One way around this is to shim node-tape in for browser testing, but
- there appear to be differences between `assert.throws()` handling between tap and tape -- I'm not sure yet, but tap may not actually respect the RegEx as the second `expected` argument, while tape does.
- tests rely on `process.env.MapboxAccessToken`

My first experiment was with [karma](http://karma-runner.github.io/0.13/index.html), and there was [a karma plugin](https://github.com/jsok/karma-env-preprocessor) that I could use to deal with the `process.env` issue, but I'm hoping that there are better, hopefully thinner, ways to deal with this. I'm still planning to take a look at other options.

**Comment by tmcw** [comment]
> tests rely on process.env.MapboxAccessToken

`envify` will fix this

**Comment by rclark** [comment]
So far on the trail of the client-side test:
- phantomjs: can't make cross-origin requests outside of a "page" context, so you can't just `phantomjs browserified-tests.js`. Running a server to provide an HTML page seems like overkill.
- karma: seems to work, by basically running the server that seems like overkill ^^
- smokestack | tap-status: not sure how to integrate it with travis without requiring everyone test on firefox

However you slice it, tests are bringing back mixed results. It appears that the superagent response object's `body` is not always set, notably with the geocodeForward tests. I am still investigating, but at the same time curious about the motivation behind superagent? Is there any reason to think httpify would be easier / more consistent / better documented?

**Comment by tmcw** [comment]
> Is there any reason to think httpify would be easier / more consistent / better documented?

[httpify looks basically abandoned](https://github.com/scottcorgan/httpify/graphs/contributors) - I'm not in love with superagent's style but it

* doesn't trigger browserify's http library
* is way smaller than `request`
* is pretty popular and well-maintained

I haven't found a better isomorphic ajax library so far (surprisingly) but will keep looking.

**Comment by tmcw** [comment]
A PR: https://github.com/mapbox/mapbox-sdk-js/pull/28

**Comment by Sequoia** [comment]
Is there an example for this? I'd like to set up my code using Browserify & it's not clear to me how to get access to the `L` object everything seems to be associated with [here](https://www.mapbox.com/mapbox.js/api/v2.4.0/l-mapbox-map/)

**Comment by tmcw** [comment]
@Sequoia looks like you're looking for Mapbox.js - that repository is over at [mapbox/mapbox.js](http://github.com/mapbox/mapbox.js) and [there are tips for how to use it with browserify](https://github.com/mapbox/mapbox.js#usage-with-browserify).
