### ISSUE TITLE
How to use Uuid in directions response?

### ISSUE THREAD

**Issue by remypalto** [mapbox/mapbox-sdk-js#199]
Hello guys,

In the response to a Directions API call, there is a field named 'uuid' at the root of the response object whose purpose seems to be internally. Is there a way to use it to kind of 'replay' a request later?

I'm not sure if it's the right place to ask but I could'nt find any repository about the API, feel free to move this issue :)
Thanks

**Comment by andrewharvey** [comment]
I'm not sure since that field isn't documented https://www.mapbox.com/api-documentation/#directions. Since this specific to the API and not this JS SDK probably better ask Mapbox Support at https://www.mapbox.com/contact/support/

**Comment by davidtheclark** [comment]
Good answer, @andrewharvey: if it's not documentation at https://www.mapbox.com/api-documentation/ then it's not really supported; but Mapbox Support but be able to help with your use case.
