### ISSUE TITLE
Getting a "options must be an object at invariant" error at line 141 (vue.client.geocodeForward(vue.addBar.address))

### ISSUE THREAD

**Issue by Grapetoast** [mapbox/mapbox-sdk-js#207]
Using vuejs 

`      submit () {
        let vue = this
        vue.client = new MapboxClient(vue.mapboxToken)
        vue.client.geocodeForward(vue.addBar.address)
          .then(function (res) {
            vue.addBar.coordinates = res.entity.features.geometry.coordinates
          })
          .catch(function (error) {
            console.log(error)
            vue.error = true
          })
        vue.postBar()
      },`

**Comment by andrewharvey** [comment]
See my comment at https://github.com/mapbox/mapbox-sdk-js/pull/205#issuecomment-370301566, I believe this was fixed recently in master. Could you upgrade to master and confirm that fixes the issue?

The PR for a new release is at https://github.com/mapbox/mapbox-sdk-js/pull/206

**Comment by andrewharvey** [comment]
The workaround in the meantime, you could try passing `{}` as the options?

**Comment by andrewharvey** [comment]
@Grapetoast This should be fixed in v1.0.0-beta10 (on github, should be in npm soon). Please post back if it's not.
