### ISSUE TITLE
Revitalization of mapbox-sdk-js

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-sdk-js#211]
**Summary: Mapbox is planning a rewrite of our JS SDK, and we'd appreciate your feedback.**

mapbox-sdk-js has been stuck in "maintenance mode" limbo for quite a while. I think there are two main reasons for this:

- mapbox-sdk-js wasn't designed to be used in Mapbox Studio and similar projects, so Mapboxers aren't using the library regularly, pushing its limits, forcing it to stay up-to-date.
- Some low-level details of the current code make it difficult or impossible to support many changes that we'd want or need in order to increase adoption.

Internally, we've been prototyping a design that addresses these problems. The core of this new JS SDK consists of client, request, response, and error objects; and on top of that core we've implemented interfaces that work in Node, in regular public websites, and in Mapbox apps like Studio and our Account Dashboard.

The new request, response, and error objects — instead of just regular errors and JSON response bodies — provide an extensible foundation for new features. With our internal prototype, we've been able to [improve error handling](https://github.com/mapbox/mapbox-sdk-js/issues/23), [abort requests](https://github.com/mapbox/mapbox-sdk-js/issues/89), [make pagination easy](https://github.com/mapbox/mapbox-sdk-js/issues/137), and more.

And since Mapbox Studio is the ultimate power user of many Mapbox APIs, Studio's usage of the core SDK code will ensure that the open source library is robust and useful.

Logistically, I think we could do the following:

- Keep this repo, but replace the codebase. It contains useful history, and we'll still want to attend to outstanding issues. When the time is ripe, we'll move the new library here so development continues in the open, with a feature branch that will eventually overwrite master.
- When the new library is ready, we'll release it as a new npm package named `@mapbox/mapbox-sdk`. We'll deprecate the `mapbox` package.

**Any feedback about this repo/package plan ^^?**

Below, I'll paste a draft of overview documentation for the new library. **I'd love any feedback about the library's API from folks within or outside Mapbox.**

---

<details>
<summary>Expand to read about details of the new library</summary>

## Usage

There are 3 basic steps to getting an API response:

1. Create a client.
2. Create a request.
3. Send the request.

### Creating requests in Node

To **create a client**, import the factory function from `'@mapbox/mapbox-sdk-js/node'` and provide it with your access token.

All services are available on `mapboxClient.services`, so all service methods are available at `mapboxClient.services[serviceName][methodName]`.

To **create a request**, invoke a service method.

Once you've created a request, **send the request** with its `send` method.
The Node client sends API requests using [`got`], a thin wrapper around Node's [`http`] module.

```js
const createNodeClient = require('@mapbox/mapbox-sdk-js/node');
const mapboxClient = createNodeClient({ accessToken: MY_ACCESS_TOKEN });

// Create a style.
mapboxClient.services.styles.createStyle({..})
  .send()
  .then(resp => {..}, err => {..});

// List tilesets.
mapboxClient.services.tilesets.listTilesets()
  .send()
  .then(resp => {..}, err => {..})
```

### Creating requests in the browser

Unlike in Node, all services are *not* attached to every browser client.
The goal is to minimize your browser bundle size; instead of bloating the bundle with every Mapbox service, you selectively import the services that you are using.
This means that there are two steps to creating a client in the browser: **create a base client, and create a service client**.

To create a base client, import the factory function from `'@mapbox/mapbox-sdk-js/browser'` and provide it with your access token.
The base client configures all the service clients you create with it, and through those service clients configure your requests.

To create a service client, import a factory function from `'@mapbox/mapbox-sdk-js/browser/services/*'` and do one of the following:

- When instantiating your base client, add the service to the base client via the `service` option.
  The service is then available on the base client's `services` property.
- After instantiating your base client, add the service to the base client via `baseClient.addService(Service)`.
  As above, the service is then available on the base client's `services` property.
- Create a standalone service client by by invoking the factory function and passing it your base client.

Each method is exemplified below.

To **create a request**, invoke a method on a service client.

Once you've created a request, **send the request** with its `send` method.
The browser client sends API requests using [`XMLHttpRequest`].

```js
const createBrowserClient = require('@mapbox/mapbox-sdk-js/browser');
const stylesService = require('@mapbox/mapbox-sdk-js/browser/services/styles');
const tilesetsService = require('@mapbox/mapbox-sdk-js/browser/services/tilesets');

// Add services to the base client as an option.
const baseClientA = createBrowserClient({
  accessToken: MY_ACCESS_TOKEN,
  services: [stylesService, tilesetsService]
});
baseClientA.services.styles.createStyle({..})
  .send()
  .then(resp => {..}, err => {..});

// Add services to the base client with addService.
const baseClientB = createBrowserClient({ accessToken: MY_ACCESS_TOKEN });
baseClientB.addService(stylesService);
baseClientB.addService(tilesetsService);
baseClientB.services.tilesets.listTilesets()
  .send()
  .then(resp => {..}, err => {..});

// Create standalone service clients.
const baseClientC = createBrowserClient({ accessToken: MY_ACCESS_TOKEN });
const stylesClient = stylesService(baseClientC);
const tilesetsClient = tilesetsService(baseClientC);
stylesClient.createStyle({..})
  .send()
  .then(resp => {..}, err => {..});
tilesetsClient.listTilesets()
  .send()
  .then(resp => {..}, err => {..});
```

### Sending requests and receiving responses

Node and browser clients use the same classes for requests, responses, and errors.

#### `MapiRequest`

Service methods return `MapiRequest` objects.

Typically, you'll create a `MapiRequest` then `send` it.
`send` returns a `Promise` that resolves with a `MapiResponse` or rejects with a `MapiError`.

`MapiRequest`s also expose other properties and methods that you might use from time to time.
For example:

- `MapiRequest#abort` aborts the request.
- `MapiRequest#eachPage` executes a callback for each page of a paginated API response.
- `MapiRequest.emitter` exposes an event emitter that fires `downloadProgress` and `uploadProgress` events.

For more details, please read the full `MapiRequest` documentation.

```js
const createNodeClient = require('@mapbox/mapbox-sdk-js/node');
const mapboxClient = createNodeClient({ accessToken: MY_ACCESS_TOKEN });
const stylesService = mapboxClient.services.styles;
const tilesetsService = mapboxClient.services.tilesets;

// Create a request and send it.
stylesService.createStyle({..})
  .send()
  .then(resp => {..}, err => {..});

// Abort a request.
const req = tilesetsService.listTilesets();
req.send().then(resp => {..}, err => {
  // Because the request is aborted, an error will be thrown that we can
  // catch and handle.
});
req.abort();

// Paginate through a response.
tilesetsService.listTilesets().eachPage((err, resp, done) => {
  // Do something with the response, then call done() to send the request
  // for the next page.
});

// Listen for uploadProgress events.
const req = stylesService.createStyleIcon({..});
req.on('uploadProgress', event => {
  // Do something with the progress event information.
});
req.send().then(resp => {..}, err => {..});
```

#### `MapiResponse`

When you `send` a `MapiRequest`, the returned `Promise` resolves with a `MapiResponse`.

Typically, you use `MapiResponse.body` to access the parsed API response.

`MapiResponse`s also expose other properties and methods.
For example:

- `MapiResponse#hasNextPage` indicates if there is another page of results.
- If there is another page, `MapiResponse#nextPage` creates a `MapiRequest `that you can `send` to get that next page.
- `MapiResponse.headers` exposes the parsed HTTP headers from the API response.

For more details, please read the full `MapiResponse` documentation.

```js
const createNodeClient = require('@mapbox/mapbox-sdk-js/node');
const mapboxClient = createNodeClient({ accessToken: MY_ACCESS_TOKEN });
const stylesService = mapboxClient.services.styles;
const tilesetsService = mapboxClient.services.tilesets;

// Read a response body.
stylesService.getStyle({..})
  .send()
  .then(resp => {
    const style = resp.body;
    // Do something with the style.
  }, err => {..});

// Get the next page of results.
tilesetsService.listTilesets()
  .send()
  .then(resp => {
    if (resp.hasNextPage()) {
      const nextPageReq = resp.nextPage();
      nextPageReq.send().then(..);
    }
  }, err => {..});

// Check the headers.
tilesetsService.listTilesets()
  .send()
  .then(resp => {
    console.log(resp.headers);
  }, err => {..});
```

#### `MapiError`

When you `send` a `MapiRequest`, the returned `Promise` might reject with a `MapiError`.

`MapiError`s expose the information you'll need to handle and respond to the error.
For example:

- `MapiError.message` tells you what went wrong.
- `MapiError.type` exposes the type of error, so you'll know if there were invalid request parameters, an HTTP error, the request was aborted, etc.
- `MapiError.statusCode` exposes the status code of HTTP errors.

For more details, please read the full `MapiError` documentation.

```js
const createNodeClient = require('@mapbox/mapbox-sdk-js/node');
const mapboxClient = createNodeClient({ accessToken: MY_ACCESS_TOKEN });
const stylesService = mapboxClient.services.styles;

// Check the error.
stylesService.getStyle({..})
  .send()
  .then(resp => {..}, err => {
    if (err.type === 'RequestAbortedError') {
      return;
    }
    console.error(error.message);
  });
```

[`got`]: https://github.com/sindresorhus/got
[`http`]: https://nodejs.org/api/http.html
[`xmlhttprequest`]: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

</details>

---

cc @andrewharvey @emilymdubois

**Comment by nitaliano** [comment]
This is a great idea @davidtheclark, I've been using this current SDK in react native and have been pushing others in the community to use this SDK as well.

React Native is fetch based so if we could keep that in mind when implementing the http clients that would be great, and I would be happy to help out test/implement anything that we would specifically need to get this working on RN.

**Comment by davidtheclark** [comment]
@nitaliano Thanks for chiming in! My plan was to use `XMLHttpRequest` to reduce the need for polyfills, and it looks like [React Native supports XHR also](https://facebook.github.io/react-native/docs/network.html#using-other-networking-libraries) — so we should be ok, right? I'll definitely take you up on your offer to test things out 👍

**Comment by nitaliano** [comment]
I didn't even realize that XHR was supported yea from the looks of the documentations that should work! Let me know when you want me to test things out.

**Comment by andrewharvey** [comment]
@davidtheclark Appreciate the update, and good to hear the js sdk is getting some more :heart:

With the current mapbox-sdk-js you can write a library built on mapbox-sdk-js which works in Node and the browser (via browserify) without any special code paths for the different environments. Would this be not possible with the new mapbox-sdk-js?

> Keep this repo, but replace the codebase. It contains useful history, and we'll still want to attend to outstanding issues. When the time is ripe, we'll move the new library here so development continues in the open, with a feature branch that will eventually overwrite master.
> When the new library is ready, we'll release it as a new npm package named @mapbox/mapbox-sdk. We'll deprecate the mapbox package.

That approach sounds spot on.

>MapiRequest#abort aborts the request.
>MapiRequest#eachPage executes a callback for each page of a paginated API response.
>MapiRequest.emitter exposes an event emitter that fires downloadProgress and uploadProgress events.

Being able to abort requests and get download/upload progress is awesome.

There are many use cases where you don't want to deal with pagination, with the current mapbox-sdk-js I use https://github.com/alantgeo/mapbox-backup/blob/master/mapbox-transparent-pagination.js to make pagination transparent via the listALL* methods. Would it be possible to make pagination transparent to the api user with the new mapbox-sdk-js?

> When you send a MapiRequest, the returned Promise resolves with a MapiResponse.

Are there any uses for creating a request without sending it? Would the api surface be simpler by automatically sending when the request is created?

> const createBrowserClient = require('@mapbox/mapbox-sdk-js/browser');
> const stylesService = require('@mapbox/mapbox-sdk-js/browser/services/styles');
> const tilesetsService = require('@mapbox/mapbox-sdk-js/browser/services/tilesets');

What about something like this?

    import { stylesService, tilesetsService } from '@mapbox/mapbox-sdk-js'

> send returns a Promise

Does that mean the new `mapbox-sdk-js` won't support IE11? Would it work with a polyfill?

**Comment by davidtheclark** [comment]
Thanks for the suggestions and questions, @andrewharvey.

> With the current mapbox-sdk-js you can write a library built on mapbox-sdk-js which works in Node and the browser (via browserify) without any special code paths for the different environments. Would this be not possible with the new mapbox-sdk-js?

I believe we should be able to do this the same way it's being done now, by specifying a `"browser"` field in the `package.json`. (Right now that's done [in the `rest` dependency](https://github.com/cujojs/rest/blob/a2661df8795ddec1a5c46ecd05deca45cf720c3a/package.json#L42).)

> Would it be possible to make pagination transparent to the api user with the new mapbox-sdk-js?

> Are there any uses for creating a request without sending it?

I think the first question here points to an answer for the second 😄

The current plan includes a `request.eachPage` method for iterating over pages — so you'd create the request and call `eachPage` *instead of* `send`. While prototyping we've also implemented a `request.collectAllPages` method, and I was just today musing about whether we should include that or not (and looking back on the discussion in https://github.com/mapbox/mapbox-sdk-js/issues/137). I agree with the point in #137 that it shouldn't be the default behavior — but maybe we expose it and let the user decide. If we *do* expose it, I'm wondering if it should come with a built-in limit or not. (The advantage of `eachPage` over `collectAllPages` is that it won't blow up if you have tons of pages.)

Exposing those pagination methods on the request object is one reason for not sending right away. Another is to make the request object an event emitter that emits progress events. And in the future we might come up with more things to do with "request" besides just sending it. (I'm also trying to learn from the ways that the current codebase's simplicity ended up *limiting* its extensibility.)

> import { stylesService, tilesetsService } from '@mapbox/mapbox-sdk-js'

The plan for the Node client is to automatically expose all services, so you wouldn't need to import individual ones. For the browser client, we want to minimize the amount of code that you'll end up bundling. Named exports might do that if you have a build system with tree shaking that works properly, but I think a more universally effective approach is to actually import/require separate modules.

We could play with ways to build the npm package so a path like `@mapbox/mapbox-sdk-js/browser/services/styles` isn't quite so long, but it's not a big concern.

> Does that mean the new mapbox-sdk-js won't support IE11? Would it work with a polyfill?

Yeah, we'd ask the user to bring their own polyfill of choice. Two goals there: to minimize bundle size and avoid polyfill conflicts. I'd like to document a list of the JS that's not pretty-much-universal so users who need to can polyfill it. (Might just be `Promise` and `Object.keys`, though we could avoid `Object.keys` if necessary.)

**Comment by andrewharvey** [comment]
@davidtheclark That sounds all good, looking forward to seeing some code I can test out.

**Comment by mikemorris** [comment]
If you're on board with requiring user-provided polyfills for IE11 support (which I think is reasonable at this point), moving from `XMLHttpRequest` to `fetch` [probably makes sense as well](https://caniuse.com/#feat=fetch).

Improved error handling and cancellable requests all sound great, would be good to confirm that the Promise implementation will play nice with `async/await` too.

Aligning the module interface between Node.js and browser such that the user-facing APIs are consistent would be nice, I'm somewhat indifferent to named exports vs individual import/requires, but the goal of minimizing bundle size for browsers is 👍

**Comment by andrewharvey** [comment]
> If you're on board with requiring user-provided polyfills for IE11 support (which I think is reasonable at this point), moving from XMLHttpRequest to fetch probably makes sense as well.

That sounds reasonable to me too.

**Comment by davidtheclark** [comment]
> moving from XMLHttpRequest to fetch probably makes sense as well.

I'm not sure there's a reason to do that, since the end-user will not be exposed to the mechanism — they'll have the same API whether we use XHR of `fetch`. We already have the implementation working with XHR, and no polyfill is needed for that, so I'm inclined to stick with it unless there are benefits to using `fetch` *behind the scenes*.

> would be good to confirm that the Promise implementation will play nice with async/await too

Since we'll use native Promises when they're available, it'll work. If the user's polyfill of choice has also been shown to work fine with `async`/`await` (after it's compiled by Babel or something, I presume?), everybody should be fine. But yeah, we'll check and make sure that's true.

I'm hoping to have some code up on a branch soonish.

**Comment by mikemorris** [comment]
@davidtheclark Biggest backend benefits to `fetch` would be [support for service workers](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith) and native Promise integration. There's also been some work on making aborting requests more consistent with [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

> XMLHttpRequest has been abortable for years, but the spec was pretty vague. It wasn't clear at which points the underlying network activity could be avoided, or terminated, or what happened if there was a race condition between abort() being called and the fetch completing.
https://developers.google.com/web/updates/2017/09/abortable-fetch

Not sure that any of this would be essential, but could be useful.

**Comment by davidtheclark** [comment]
Version 0.1.0 of `@mapbox/mapbox-sdk` is now released, and `mapbox` is deprecated with the message `Please switch to the @mapbox/mapbox-sdk package. See documentation at https://github.com/mapbox/mapbox-sdk-js`

**Comment by andrewharvey** [comment]
great work on this @davidtheclark @kepta happy to see it published!
