### ISSUE TITLE
Static API : Color in geojson properties not supported because of # non-encoding

### ISSUE THREAD

**Issue by philippeauriach** [mapbox/mapbox-sdk-js#212]
Hi,
I'm having trouble styling a static url with a simple-style in properties.

my geojson is the following : 
```
{
    type: 'FeatureCollection',
    features: [
        { ...newGeoJson, id: 'target', properties: { stroke: 'green', fill: 'red' } },
        { ...zebbox, id: 'bbox', properties: { 'stroke-opacity': 0, 'fill-opacity': 0 } }
    ]
}
``` 
This one works fine (with 'red' and 'green'), but does not work when I put the following :
```properties: { stroke: '#429F8D', fill: '#429F8D' } }```
This cause the url rendered with and hashtag (not escaped) and therefore the url doesn't work. (if I construct the url manually and set %23 in place of the #, it works fine).

If I fill the properties like this : 
```properties: { stroke: '%23429F8D', fill: '%23429F8D' } }```
then the % character is replaced and therefore, it does'nt work.

I'm going to look through the lib, see if I can find where this problem comes from. In the meantime, does anyone had the same problem ? Is there any workaround I could use ?

**Comment by philippeauriach** [comment]
The lib uses rest/util/uriTemplate to create the url (this file : https://github.com/cujojs/rest/blob/master/util/uriTemplate.js) 
It seems to treat # differently, which is understandable as it should be treated as an hashtag in an url.

I don't see an easy way to solve this, except for this ugly workaround :
`mapboxClient.getStaticURL(...).replace(new RegExp('#429F8D', 'g'), '%23429F8D')`

I think a global a complete solution would be to change the way the url is computed, as uriTemplate does not seem to support custom character encoding / configuration.
Maybe we should add this in the doc ? (I remember seeing in the mapbox static doc that simple format is supported).

Thanks

**Comment by davidtheclark** [comment]
The newly published `@mapbox/mapbox-sdk` avoids this problem by trimming the `#` from your input. Please re-open if the problem persists, or open new issues with new problems 😄
