### ISSUE TITLE
TypeScript definitions for mapbox-sdk-js

### ISSUE THREAD

**Issue by ctaggart** [mapbox/mapbox-sdk-js#213]
I have not been able to find TypeScript definitions for this repository. Are there any? If not, please consider this a feature request.

**Comment by kepta** [comment]
Happy to take a pull request for typescript types.

**Comment by m00dy** [comment]
PLEASE PLEASE PLEASE :)

**Comment by AndyCJ** [comment]
I've done the typings for the MapiClient, and the Geocoder Service.

 - They aren't complete.
 - They aren't very well tested.
 - They don't have documentation.

But, they can be a starting point for anyone else who's interested...

Hopefully someone finds them useful.

<details>
	<summary>mapbox-sdk.d.ts</summary>

    declare module "@mapbox/mapbox-sdk" {
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#coordinates
        export type Coordinates = [number, number];
    
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#boundingbox
        export type BoundingBox = [number, number, number, number];
    
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/classes.md#mapirequest
        export type Emitter = 'response' | 'error' | 'downloadProgress' | 'uploadProgress';
    
        export interface MapiRequest {
            emitter: Emitter;
            client: MapiClient;
    
            response: MapiResponse | null;
            error: MapiError | Error | null;
    
            aborted: boolean;
            sent: boolean;
    
            path: string;
            origin: string;
            method: string;
            query: Object;
            params: Object;
            headers: Object;
    
            body?: Object | string;
            file?: Blob | ArrayBuffer | string;
    
            url: (accessToken?: string) => string;
            send: () => Promise<MapiResponse>;
            abort: () => void;
            eachPage: (callback: EachPageCallback) => void;
            clone(): MapiRequest;
        }
    
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/classes.md#eachpage
        export interface EachPageCallback {
            (error: MapiError, response: MapiResponse, next: () => void): void;
        }
    
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/classes.md#mapiresponse
        export interface MapiResponse<TBody extends Object = Object> {
            body: TBody;
            rawBody: string;
            statusCode: number;
            headers: Object;
            links: Object;
            request: MapiRequest;
    
            hasNextPage(): boolean;
            nextPage(): MapiRequest | null;
        }
    
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/classes.md#mapierror
        export type RequestAbortedErrorType = 'RequestAbortedError';
        export type HttpErrorType = 'HttpError';
        export type ErrorType = RequestAbortedErrorType | HttpErrorType;
    
        export interface MapiRequestAbortedError {
            request: any;
            type: RequestAbortedErrorType;
            message?: string; // TODO is the message availible on RequestAbortedError?
        }
    
        export interface MapiHttpError {
            request: any;
            type: HttpErrorType;
    
            statusCode: number;
            body: Object | string;
            message?: string; // TODO is the message always availible on HttpError?
        }
    
        export type MapiError = MapiRequestAbortedError | MapiHttpError;
    
        // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/classes.md#mapiclient
        export interface MapiClient {
        }
    
        export interface MapiClientFactoryArgs {
            accessToken: string;
            origin?: string;
        }
    
        export interface MapiClientFactory {
            (args: MapiClientFactoryArgs): MapiClient;
        }
    
        const mapiClientFactory: MapiClientFactory;
    
        export default mapiClientFactory;
    }
    
    // https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#geocoding
    declare module "@mapbox/mapbox-sdk/services/geocoding" {
        import * as MapboxSdk from "@mapbox/mapbox-sdk";
    
        export type GeocodingType = "country" | "region" | "postcode" | "district" | "place" | "locality" | "neighborhood" | "address" | "poi" | "poi.landmark";
        export type GeocodingMode = "mapbox.places" | "mapbox.places-permanent";
        export type GeocodingReverseMode = "distance" | "score";
    
        export interface ForwardGeocodeConfig {
            query: string;
            mode: GeocodingMode;
            countries?: string[];
            proximity?: MapboxSdk.Coordinates;
            types?: GeocodingType[];
            autocomplete?: boolean;
            bbox?: MapboxSdk.BoundingBox;
            limit?: number;
            language?: string[];
        }
    
        export interface ReverseGeocodeConfig {
            query: string;
            mode: GeocodingMode;
            countries?: string[];
            types?: GeocodingType[];
            bbox?: MapboxSdk.BoundingBox;
            limit?: number;
            language?: string[];
            reverseMode?: GeocodingReverseMode;
        }
    
        export interface GeocoderService {
            forwardGeocode: (config: ForwardGeocodeConfig) => MapboxSdk.MapiRequest; // TODO - Response Typing https://www.mapbox.com/api-documentation/#response-object
            reverseGeocode: (config: ReverseGeocodeConfig) => MapboxSdk.MapiRequest; // TODO - Response Typing https://www.mapbox.com/api-documentation/#response-object
        }
    
        export interface GeocoderServiceFactory {
            (mapiClient: MapboxSdk.MapiClient): GeocoderService;
        }
    
        const geocoderServiceFactory: GeocoderServiceFactory;
    
        export default geocoderServiceFactory;
    }
</details>

**Comment by mikeomeara1** [comment]
Opened [PR#294](https://github.com/mapbox/mapbox-sdk-js/pull/294) but until it's merged/etc. see here for what are fairly complete (although not fully tested) types: [https://raw.githubusercontent.com/mikeomeara1/mapbox-sdk-js/typescript-typings/types/index.d.ts](https://raw.githubusercontent.com/mikeomeara1/mapbox-sdk-js/typescript-typings/types/index.d.ts)

**Comment by davidtheclark** [comment]
Sorry for the mixup here. We are not going to maintain TypeScript definitions at this time. Please use DefinitelyTyped, instead. 

Emoji reactions to the original comment are appreciated so that we can gauge interest for future considerations.

**Comment by John0x** [comment]
This seems to have been requested quite a lot. Are there any new plans yet?
Having a js lib without typings is kinda weird nowadays especially for typescript projects

**Comment by andrewharvey** [comment]
> Having a js lib without typings is kinda weird nowadays and keeps a lot of people from using it.

Does it? To be honest I have zero knowledge of TypeScript, but I thought that you could use the externally maintained types at DefinitelyTyped?

As someone who contributes to this library, it's enough work as it is maintaining and adding new features and I worry that adding TS here would increase the barrier for new contributions and maintenance so I'm against adding them directly here.

**Comment by John0x** [comment]
> > Having a js lib without typings is kinda weird nowadays and keeps a lot of people from using it.
> 
> Does it? To be honest I have zero knowledge of TypeScript, but I thought that you could use the externally maintained types at DefinitelyTyped?
> 
> As someone who contributes to this library, it's enough work as it is maintaining and adding new features and I worry that adding TS here would increase the barrier for new contributions and maintenance so I'm against adding them directly here.

I would personally rather write the lib on my own than use one without typings.
There seem to be two packages for the mapbox typings:
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mapbox
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox__mapbox-sdk/index.d.ts

The first one looks heavily outdated, I only found the second one just now. The second one looks up-to-date though, so that might solve the issue. Sorry, didn't see that before. It would probably be good to mention the package in the Readme. 
`yarn add @types/mapbox__mapbox-sdk -D`

**Comment by andrewharvey** [comment]
going by https://github.com/mapbox/mapbox-sdk-js/pull/294/files it looks like TypeScript support doesn't need to change any of the library source code, it's just a single external ts file. If that's the case, is there any downside to it being maintained external, or any upside to being stored internal to this repo?

**Comment by John0x** [comment]
Yes, it can be just a single external ts file (doesn't have to be though). In my opinion it's better if you have the typings in the lib directly, especially if there is still active development. The typings would be installed automatically instead of having to install a separate package and they could probably (if they are being maintained) be kept up-to-date more easily.

If there aren't any typings included you'd typically try to install the typings package of it, which is normally called '@types/packagename' (for example '@types/mapbox-sdk'). That doesn't exist though, which most likely leads to people thinking that there aren't any typings for the mapbox-sdk.

**Comment by SKalt** [comment]
`mapbox-sdk-js` already uses JSDoc typedefs and annotations which `tsc`, the typescript compiler, can convert to a stubfile.  I've got an attempt at automating the stub-file-from-jsdoc generation over at #361. I'll get around to testing the generated stubs within a week.

I'll second that: 
- I think maintaining the type definitions as close to the source code as possible reduces the risk of them losing sync with the source code.
- the lack of stubs did prevent me from using this library.
