### ISSUE TITLE
geocodeReverse not limiting types

### ISSUE THREAD

**Issue by ctaggart** [mapbox/mapbox-sdk-js#214]
Like [the examples](https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/geocoding.js#L200-L212), I'm trying to limit the `types` returned for reverse geocoding to just `address`. 

Any idea why this is returning all types:
``` ts
const rsp = await mapbox.geocodeReverse({longitude: e.geometry.coordinates[0], latitude: e.geometry.coordinates[1], options: { types: 'address'}})
```

May be related to https://github.com/mapbox/mapbox-sdk-js/pull/197.

**Comment by fighterii** [comment]
Hey,

i had the same issue, could you try passing the options as an extra object (at least thats what the geocoding.js expects i assume):

`const rsp = await mapbox.geocodeReverse({longitude: e.geometry.coordinates[0], latitude: e.geometry.coordinates[1]}, {options: { types: 'address'}})`

**Comment by andrewharvey** [comment]
Good catch @ctaggart and @fighterii. The example is wrong, it should be:

```js
var mapboxClient = new MapboxClient('ACCESSTOKEN');
mapboxClient.geocodeReverse(
  { latitude: 33.6875431, longitude: -95.4431142},
  { types: 'address', limit: 3 },
  function(err, res) {
  // res is a GeoJSON document with up to 3 geocoding matches
});
```
