### ISSUE TITLE
Error handling and documentation

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-sdk-js#23]
The various client methods should handle errors in a regular, predictable fashion, and there should be a well-defined way to document the possible error outcomes from each method.

**Comment by tmcw** [comment]
Yep, so my going assumption would be that

* Bad arguments throw Error objects. We can add a `@throws` tag to indicate this
* Otherwise errors from servers should have >=400 statuses and the errors that come back should be un-modified response bodies from the ajax call

**Comment by rclark** [comment]
It looks to me like the superagent error object is probably TMI -- make sense to add a helper that returns an error object with just these things (status + message)?

Also, often the API response will be

```
{ "Message": "The thing does not exist" }
```

Do we want the error object to include that as a javascript object? as a JSON string? or just the message?

**Comment by rclark** [comment]
cc @willwhite a little more food for thought wrt errors.

**Comment by rclark** [comment]
It appears that superagent's error object contains a js `Error` object at `err.response.error`. How about we just make the method calls return that? e.g.

```js
request(url, function(err, res) {
  if (err) return callback(err.response.error);
  callback(res.body);
}
```

**Comment by rclark** [comment]
btw here's the `console.log` of such an error object:

```
{ [Error: cannot GET /datasets/v1/rclark/peanuts?access_token=xxx (422)]
  status: 422,
  text: '{"message":"No dataset"}',
  method: 'GET',
  path: '/datasets/v1/rclark/peanuts?access_token=xxx' }
```

**Comment by rclark** [comment]
Here's one potential approach to handling the error objects that come back from superagent: https://github.com/mapbox/mapbox-sdk-js/compare/errors

If folks are onboard I'll clean this up and test better, but I'm not wedded to the idea if there are others floating around.

**Comment by andrewharvey** [comment]
eg.

if the access token doesn't have the scope `styles:list` the following will happen:

```
mapbox.listStyles((err, styles) => {
   // err is undefined
   // styles is { message: 'This API requires a token with styles:list scope.' }
});
```

I would expect that to be returned as the err rather than within styles.

**Comment by davidtheclark** [comment]
The newly published `@mapbox/mapbox-sdk` has a (hopefully) more clear and consistent way of handling errors, which is documented. Please open a new issue if you have new problems 😄
