### ISSUE TITLE
Pre-bundled files on unpkg.com broken URLs : Cannot find package "mapbox-sdk"

### ISSUE THREAD

**Issue by violy** [mapbox/mapbox-sdk-js#244]
Hello.

In the [ReadMe unpkg.com section](https://github.com/mapbox/mapbox-sdk-js#pre-bundled-files-on-unpkgcom) sample, both URLs used seems broken, return `404` response `Cannot find package "mapbox-sdk"`. 
```HTML
<script src="https://unpkg.com/mapbox-sdk/umd/mapbox-sdk.js"></script>
<script src="https://unpkg.com/mapbox-sdk/umd/mapbox-sdk.min.js"></script>
```

works fine with :
- https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.min.js 
- https://unpkg.com/@mapbox/mapbox-sdk/umd/mapbox-sdk.js

**Comment by davidtheclark** [comment]
Closed by #245.
