### ISSUE TITLE
getDirections' config parameter is wrongly typed

### ISSUE THREAD

**Issue by chiku-samugari** [mapbox/mapbox-sdk-js#246]
Hi, I am trying version 0.1.0 installed via yarn and realized that `config.steps` option of `getDirections` is not working as it is expected. The code I tried is as follows:

    client.getDirections({
      waypoints: [
        {
          coordinates: start
        },
        {
          coordinates: goal
        }
      ],
      geometries: 'geojson',
      profile: 'walking',
      steps:true,
      overview:"full"
    })

and I got a response whose `steps` property is an empty Array. I checked the request parameter on the Firefox DevTools and found that parameter `steps` was there but the value was empty.
![screenshot](https://user-images.githubusercontent.com/3016888/41428940-84236cd2-7046-11e8-8f83-b7d2ce046dba.png)

I have tried to change `true` to `"true"` in above code, but type checking complained. I thus modified the `services/directions.js` file directly and it worked correctly.

	-    steps:v.boolean,
	+    steps: v.oneOf('true', 'false'),

According to these observation, I guess that the type assertion `v.boolean` for the properties of `config` parameter is wrong and should be `oneOf('true', 'false')`.

**Comment by kepta** [comment]
If I am not wrong, I think we need to do something similar to [this](https://github.com/mapbox/mapbox-sdk-js/blob/master/services/map-matching.js#L156). which is nothing but iterating through all properties and stringifying each boolean property.

**Comment by davidtheclark** [comment]
Yep, @kepta: I think that's the way to go 👍

**Comment by chiku-samugari** [comment]
I agree. That's better than my workaround.
