### ISSUE TITLE
 Documentation examples are incorrect/out of date

### ISSUE THREAD

**Issue by christopher-dG** [mapbox/mapbox-sdk-js#248]
Some stuff is leftover from the old version I suppose.

* [Retrieve S3 credentials](https://www.mapbox.com/api-documentation/?language=JavaScript#retrieve-s3-credentials)
  * `s3` is not instantiated anywhere with the credentials from `getCredentials`.
  * `getCredentials.then(putFileOnS3);`: should be `getCredentials().then`.
* [Create an upload](https://www.mapbox.com/api-documentation/?language=JavaScript#create-an-upload)
  * `createUpload` takes the url as `url`, but it's passed as `s3Url`.
  * `createUpload` takes the tileset name as `tilesetName`, but it's passed as `name`.

After looking through the code, it seems that some of these are already fixed, but not updated on the website (I'm not sure how that gets synced though).

**Comment by davidtheclark** [comment]
Thanks, @christopher-dG. Those upload examples need some work. We'll fix them up soon.
