### ISSUE TITLE
Incorrect lat/lng ordering in api-documentation examples

### ISSUE THREAD

**Issue by kuanb** [mapbox/mapbox-sdk-js#256]
Minor, but noticing that the examples in documentation for API client (eg Map Matching) have lat/lng ordering inverse from the order required by the API.

Example from this section: https://www.mapbox.com/api-documentation/?language=JavaScript#retrieve-a-match

```
mapMatchingClient
  .getMatching({
    points: [
      {
        coordinates: [32.712041, -117.17283],
        approach: 'curb'
      },
      {
        coordinates: [32.712256, -117.17291],
        isWaypoint: false
      },
      {
        coordinates: [32.712444, -117.17292]
      },
      {
        coordinates: [32.71257, -117.172922],
        waypointName: 'point-a',
        approach: 'unrestricted'
      },
      {
        coordinates: [32.7126, -117.172985],
        timestamp: '2018-06-08T10:48:19.307Z'
      },
      {
        coordinates: [32.712597, -117.173143]
      },
      {
        coordinates: [32.712546, -117.173345]
      }
    ],
    tidy: false,
  })
  .send()
  .then(response => {
    const matching = response.body;
  })
```

Above is the JS snippet shown in the JS example code. The coordinate values (e.g. `[32.712597, -117.173143]`) need to be reversed.

Adding a screen cap, for posterity:
![image](https://user-images.githubusercontent.com/6053396/42416434-fa68ff7c-8222-11e8-8c63-e41a72e97ee8.png)

**Comment by davidtheclark** [comment]
Thanks, @kuanb! I'll have a fix live soon.
