### ISSUE TITLE
Map matching api doesn't match docs

### ISSUE THREAD

**Issue by surdu** [mapbox/mapbox-sdk-js#275]
Looking at the [documentation for map matching api ](https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#getmatch) in this repo doesn't match [the one on the website](https://www.mapbox.com/api-documentation/?language=JavaScript#retrieve-a-match).

For example, the following configs are missing from the this api: `radiuses`, `approaches`, `waypoint_names`, etc

**Comment by davidtheclark** [comment]
Hi @surdu. `config.points` is an array of objects that contain the information you want to specify. Those objects are called `MapMatchingPoints` in the docs and fully described here: https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#mapmatchingpoint. Please re-open if there is anything you're still unable to find.
