### ISSUE TITLE
Static API: Geojson Polygon overlay

### ISSUE THREAD

**Issue by danielduhh** [mapbox/mapbox-sdk-js#283]
Is there an example of how to use a Polygon Feature as a geojson overlay to generate a static map? Right now, I'm unable to do so with the following geojson. However, LineStrings and Points work fine.

geojson:
```json
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[0,0],[0,1],[1,1],[1,0]]},"properties":{"fill":"#555555"}}]}
```

API reponse:
```json
{"message":"Failed parsing geojson"}
```

Here's a code snippet:
```javascript
  const request = staticClient
    .getStaticImage({
      ownerId: 'mapbox',
      styleId: 'light-v9',
      width: 200,
      height: 300,
      position: 'auto',
      overlays: [{
        geoJson: geojson
      }]
    })

  const staticImageUrl = `${request.url()}?access_token=${API_TOKEN}`;
```

Interestingly, if you use a enclosed Polyline, and add the "fill" property to the geojson, it'll render the overlay.
See:
```json
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"LineString","coordinates":[[0,0],[0,10],[10,10],[10,0],[0,0]]},"properties":{"stroke":"#f0f0f0","stroke-width":2,"fill":"#ff0000"}}]}
```
This is using the latest version (^0.4.1) of `@mapbox/mapbox-sdk` & `@mapbox/mapbox-sdk/services/static`

**Comment by davidtheclark** [comment]
Hi @danielduhh. Looks like your polygon definition is invalid GeoJSON. `"coordinates":[[0,0],[0,1],[1,1],[1,0]]` is just a linear ring coordinate array; but the `"coordinates"` value for a polygon needs to be an *array* of linear ring coordinate arrays. Also, the first and last positions in each ring need to match. http://geojsonlint.com/ or another tool for verifying the validity of your GeoJSON should help.

**Comment by abelcallejo** [comment]
> Hi @danielduhh. Looks like your polygon definition is invalid GeoJSON. `"coordinates":[[0,0],[0,1],[1,1],[1,0]]` is just a linear ring coordinate array; but the `"coordinates"` value for a polygon needs to be an _array_ of linear ring coordinate arrays. Also, the first and last positions in each ring need to match. http://geojsonlint.com/ or another tool for verifying the validity of your GeoJSON should help.

Wasted hours to figure it out, the only thing that went wrong with me was not making the ring. It only worked for me by making the first point equivalent to the last point.
