### ISSUE TITLE
Required module not found

### ISSUE THREAD

**Issue by lamnguyen2187** [mapbox/mapbox-sdk-js#285]
I got the above error trying to import `@mapbox/mapbox-sdk/services/geocoding` in a JS file. Note that I have already installed `@mapbox/mapbox-sdk` successfully with `npm install @mapbox/mapbox-sdk`. What am I missing?

**Comment by lamnguyen2187** [comment]
Just realized this error is coming from Flow. Is there a way to inform Flow that `@mapbox/mapbox-sdk/services/geocoding` really points to a valid module?

**Comment by davidtheclark** [comment]
@lamnguyen2187: That module should exist, and Flow should find it without any trickery. Does your code actually work, despite the Flow error? Could you check your `node_modules` directory and see if the file exists where it should?

**Comment by lamnguyen2187** [comment]
@davidtheclark: Because of this flow error, my code does not pass Flow check and the entire build fails. 

Here is where `@mapbox/mapbox-sdk` is installed in `node_modules`. I did not see any problem with it.

![image](https://user-images.githubusercontent.com/39612646/46741769-49535380-ccd8-11e8-9868-0860a5e01d28.png)

**Comment by davidtheclark** [comment]
@lamnguyen2187 To further investigate this, then, I suggest turning off Flow and seeing if the code runs. I suspect there is something wrong on your end, possibly with your Flow configuration. Please re-open if you're able to isolate this problem in a way that demonstrates that this library needs a bug fix.
