### ISSUE TITLE
MIPS ABI

### ISSUE THREAD

**Issue by kidandcat** [mapbox/mapbox-sdk-js#287]
I'm getting an error because mapbox is trying to use MIPS ABi, and it has been retired in Android NDK, Revision r17c (June 2018):

Support for ARMv5 (armeabi), MIPS, and MIPS64 has been removed. Attempting to build any of these ABIs will result in an error.

am I wrong? is any work already in progress to fix this? 

I finally could make the build, but I needed to copy an older toolchain manually into the NDK bundle.

**Comment by andrewharvey** [comment]
Did you mean to post this in this repo? This is a JavaScript library, no native code here... :confused:

**Comment by kidandcat** [comment]
Oh, then is mapbox-react-native-mapbox-gl I think, sorry
