### ISSUE TITLE
Getting message: Not Found Error when trying to create temporary token from mapbox sdk

### ISSUE THREAD

**Issue by mayankshrm77** [mapbox/mapbox-sdk-js#291]
MapiError {
  message: 'Not Found',
  type: 'HttpError',
  statusCode: 404,
  request:
   MapiRequest {
     id: 1,
     _options:
      { method: 'POST',
        path: '/tokens/v2/:ownerId',
        params: {},
        body: [Object] },
     emitter: EventEmitter { _events: {}, _eventsCount: 0 },
     client:
      NodeClient {
        accessToken:
         'my access token',
        origin: 'https://api.mapbox.com' },
     response: null,
     error: [Circular],
     sent: true,
     aborted: false,
     path: '/tokens/v2/:ownerId',
     method: 'POST',
     origin: 'https://api.mapbox.com',
     query: {},
     params: {},
     body: { expires: '2018-11-26T19:47:53.000Z', scopes: [Array] },
     file: null,
     headers: { 'content-type': 'application/json' } },
  body: { message: 'Not Found' } }

**Comment by davidtheclark** [comment]
Public keys do not have `tokens:write` scopes, so cannot create temporary tokens. For more information, please see https://www.mapbox.com/api-documentation/#access-tokens and https://www.mapbox.com/api-documentation/#access-tokens.

**Comment by mayankshrm77** [comment]
Thanks
