### ISSUE TITLE
JS SDK usage expects only directions profile and not "mapbox/" in parameter

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-sdk-js#304]
Per an earlier issue from @geografa: 

The [API docs](https://www.mapbox.com/api-documentation/navigation/#retrieve-directions) suggest the available profiles are in the form "mapbox/cycling". The JS API expects the profile and not the "mapbox/" part of the parameter. 

https://github.com/mapbox/mapbox-sdk-js/blob/master/services/directions.js#L23 

Suggested fix would be to update the [example](https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#directions) so it makes use of the routing profile parameter:

```
directionsClient
  .getDirections({
    waypoints: [
      {
        coordinates: [-122.68903,45.50015],
        approach: 'unrestricted'
      },
      {
        coordinates: [-122.677738,45.52245]
      }
    ],
    profile: "cycling"
  })
  .send()
  .then(response => {
    const directions = response.body;
  });
```

**Comment by davidtheclark** [comment]
Sure, adding a `profile` to the example sounds good 👍
