### ISSUE TITLE
datasets.createDataset does not allow geojson keys ?, type, feature

### ISSUE THREAD

**Issue by shohil06** [mapbox/mapbox-sdk-js#306]
Hey,
I have prepared geojson multiple geojson files for each territory(Geographic region - Multi-Polygon) with properties inside that geojson, I have also added "name" and "description" inside that,
But the API only allows **name** and **description** keys in json, while **Mapbox Dataset API** allows to upload geojson, 

Also [Dataset API Documentation](https://docs.mapbox.com/help/troubleshooting/uploads/#datasets), Geojson has to be sent from body,

Can anyone please put up an example on how to send geojson from mapbox javascript-sdk ?

My Sample data code which pushes it to my Mapbox dataset: 
`datasetsClient.createDataset(sampleData)
    .send()
    .then(function (response) { console.log(response) })
    .catch(function (err) { throw err; });`

NOTE: in the above code, **sampleData** is the geojson i am trying to send.
Thanks,
Regards, Shohil Sethia

**Comment by davidtheclark** [comment]
Hi @shohil06. When create a dataset with the API, you'll create an *empty* dataset first (via `createDataset`), then you'll add features to it (via `putFeature`). You cannot create the dataset and add features to it with a single API call.

I hope that clears up the misunderstanding.
