### ISSUE TITLE
Static API service `position.bearing` not added to url

### ISSUE THREAD

**Issue by chrisgo** [mapbox/mapbox-sdk-js#315]
Using example code here
https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#static

```
const request = staticClient
  .getStaticImage({
    ownerId: 'mapbox',
    styleId: 'streets-v11',
    width: 600,
    height: 400,
    position: {
      coordinates: [-122.4241, 37.78],
      zoom: 14,
      bearing: 0,
      pitch: 60,
    }
  });
const staticImageUrl = request.url();
```

The expected URL is

https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.4241, 37.78,14,0,60/600x450/600x400

but it is coming out as

https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.4241, 37.78,14,60/600x450/600x400

It is missing the `bearing` in the URL output of `encodePosition()`

The expected URL has an extra `0,` between `14,` and `60`

The code on this line
https://github.com/mapbox/mapbox-sdk-js/blob/master/services/static.js#L202

```
.filter(Boolean)
```
seems to be removing `0` due to a Boolean filter

**Comment by kepta** [comment]
@chrisgo happy to review a PR fixing this.
