### ISSUE TITLE
Does this library work with the Navigation SDK ?

### ISSUE THREAD

**Issue by dancomanlive** [mapbox/mapbox-sdk-js#316]
I wish to integrate the MapBox Navigation SDK https://www.mapbox.com/navigation-sdk/ with React Native. 

I see in the readme "A JS SDK for working with Mapbox APIs. Works in Node, the browser, and React Native." Nothing regarding the Navigation API.

Then I see a link to Directions here https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md that further links to https://docs.mapbox.com/api/navigation/#directions.

**Comment by andrewharvey** [comment]
This library is designed as a JavaScript (node and web) library to help access the Mapbox API, including directions, geocoding etc.

The Mapbox Navigation SDK is a UI library, so this is not the place for a JavaScript port of the Navigation SDK. The closest thing published by Mapbox is https://github.com/mapbox/guidance-sim, but that's a simulator.
