### ISSUE TITLE
Static image not returning binary data/string

### ISSUE THREAD

**Issue by joeyhub** [mapbox/mapbox-sdk-js#342]
I'm saving the body using Buffer.from(body, 'binary') but what I'm getting out isn't valid.

```
for(let i = 0; i < image.length; i++)
    if(image.charCodeAt(i) > 255) {
        console.log([image.charCodeAt(i), i, image[i]]);
            break;
    }
```

```[ 65533, 0, '�' ]```

65533 is javascriptese for dunno which means it tried to load as UTF8 but wasn't.

```
// First char of PNG magic.
'\x89'.charCodeAt(0)
'\u0089'.charCodeAt(0)
```

I get the same with rawBody.

Is there anyway to control this? I see perhaps some issues making the lib work on browser which might be why it's not using buffer but also even for browser if it's not using binary strings then it'll be broken there too. It seems to only be useful if you generate the URL and use that?

Is these a missing layer for conversion in the lib, IE to expect binary, JSON, etc?

I see just this:

```
  try {
    this.body = JSON.parse(responseData.body || '{}');
  } catch (parseError) {
    this.body = responseData.body;
  }
```

Technically speaking binary data can accidentally parse as JSON.

This needs an implementation for string and buffer:
```
      var body = '';
      gotStream.on('data', function(chunk) {
        body += chunk;
      });
```

And this needs to be configurable:

```
gotStream.setEncoding('utf8');
```

Which would pass down to the stream consumer used.

I don't know what happens with the browser layer but small chance I reckon that it returns binary string where as this has explicitely utf8 so will break on non-utf8.

**Comment by andrewharvey** [comment]
proposed a fix at #351
