### ISSUE TITLE
Cant set the driving-traffic profile for optimization service

### ISSUE THREAD

**Issue by froilas** [mapbox/mapbox-sdk-js#366]
On the documentation. driving-traffic is one of the profile to consider traffic data, but when I use it. I got this error. 

Error: profile must be "driving", "walking", or "cycling".

**Comment by andrewharvey** [comment]
Can you please provide a minimal reproducible example code.

**Comment by froilas** [comment]
Here is the code for sending optimization request to mapbox

`let optimizedRoute = await optimizationService.getOptimization({
      profile: 'driving-traffic',
      overview: 'full',
      roundtrip: true,
      steps: false,
      source: 'first',
      destination: 'any',
      waypoints: arLocations.map(x => {
        return {
          coordinates: [x.coordinates.lon, x.coordinates.lat]
        }
      })
    }).send();`

This is the error that I get when sending the request 

**Error: profile must be "driving", "walking", or "cycling".**

Also, On the optimization.js file. I noticed that the assertion of profile value depends on these code

`profile: v.oneOf('driving', 'walking', 'cycling'),`
