### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-sdk-js#37]
The [request URL](https://api.mapbox.com/v4/directions/mapbox.driving/-79.40184116363517%2C43.77251932100583%3B-79.40184116363517%2C43.77251932100583.json?access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJiUzBYOEJzIn0.VyXs9qNWgTfABLzSI3YcrQ) looks correct but I'm getting a 403 error using `getDirections` locally from port 3000.

**Comment by tristen** [comment]
The following works in Node but __fails in the browser__:

```js
var MapboxClient = require('mapbox');
var client = new MapboxClient('TOKEN');

client.getDirections([
  { latitude: 33.6875431, longitude: -95.4431142 },
  { latitude: 33.6875431, longitude: -95.4831142 }
], function(err, results) {
  console.log(results);
});
```

Note that this __works in the browser__:
``` js
client.geocodeForward('Chester, NJ', function(err, res) {
  console.log(res);
});
```

**Comment by chapinkapa** [comment]
I am seeing this same issue for getDirections.

**Comment by chapinkapa** [comment]
I am guessing this is a mapbox-server related issue...

**Comment by chapinkapa** [comment]
I am using port 4050 in localhost. I tried an alias also, and it is still not working.

**Comment by tmcw** [comment]
This isn't a server issue: right now the [cujojs/rest](https://github.com/cujojs/rest) mime interceptor is sending an OPTIONS request first that requires the Content-Type header, and this is rejected by the server.

**Comment by tmcw** [comment]
Actually yeah - we should probably allow the accept header.

**Comment by chapinkapa** [comment]
Any update on this? Or any workaround?

**Comment by tmcw** [comment]
We're working on a fix on the server level.

**Comment by tmcw** [comment]
:+1: fixed upstream
