### ISSUE TITLE
Return raw coordinates in matrix api request

### ISSUE THREAD

**Issue by gwuah** [mapbox/mapbox-sdk-js#374]
Hi, This problem isn't directly related to this client. But I couldn't find anywhere to ask.

So when you make a request to the matrix api, it returns a snapped coordinate instead of the original(raw) coordinate you passed in the query params.

I wanted to know if there's a way to return the raw values passed.

Thanks in advance!

**Comment by andrewharvey** [comment]
Sorry but if it's not directly something that can be addressed in this client library then best to ask Mapbox Support https://www.mapbox.com/contact/.

For your specific question, can you just keep track of your query params so then you always have your original points?
