### ISSUE TITLE
Please add a basic full example to README

### ISSUE THREAD

**Issue by mariusa** [mapbox/mapbox-sdk-js#379]
Would you please add a basic example which shows a map & geocoder, similar to
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/
?

I'm struggling to do this using Vue, without Vue wrappers which have various issues. 

eg

```
<template>
    <div>
Here's the map:
            <div id="map"  style="height: 500px; width: 100%"></div>

    </div>
</template>

<script>
//TODO how to import mapboxgl and use it here?

export default {
    data: () => ({
        accessToken: '...',
        mapStyle: 'mapbox://styles/mapbox/streets-v11',
        map: null,

    }),

    mounted() {

        this.map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [-79.4512, 43.6568],
            zoom: 13
        });

        this.map.addControl(
            new MapboxGeocoder({
                accessToken: mapboxgl.accessToken,
                mapboxgl: mapboxgl
            })
        );

    },

    methods: {
     
        handleSearch(event) {
            console.log('handleSearch', event)
        }
    },
}
</script>


```

**Comment by andrewharvey** [comment]
Hi this repository is for the Mapbox SDK for JS, which although the Mapbox Geocoder control for Mapbox GL JS uses, it's not something this library covers.

If there are issues with the example at https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ you can report them in the Mapbox GL JS docs repo at https://github.com/mapbox/mapbox-gl-js-docs. If the issue relates to the GeocoderControl you can report this at https://github.com/mapbox/mapbox-gl-geocoder, if you're not sure you can just report to either and it can be easily moved to the right place.

I use the GeocoderControl with Vue all the time without issue so it should work out of the box.

> //TODO how to import mapboxgl and use it here?

See the instructions at https://docs.mapbox.com/mapbox-gl-js/api/#quickstart under Module builder. But personally I use

```
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'
```
