### ISSUE TITLE
Doesn't work on Node 12

### ISSUE THREAD

**Issue by snowsea-dev** [mapbox/mapbox-sdk-js#414]
I am trying to install the package on node 12, and it says

node-pre-gyp info check checked for "/Volumes/SnowSea/Current/tophap-preview-v2/node_modules/@mapbox/mapbox-gl-native/lib/node-v72/mbgl.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v72-darwin-x64-Release.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v72-darwin-x64-Release.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v72-darwin-x64-Release.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Volumes/SnowSea/Current/tophap-preview-v2/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:327:22)

Doesn't it work on Node 12?

**Comment by andrewharvey** [comment]
I don't think this library includes @mapbox/mapbox-gl-native. Are you sure it's this library?

**Comment by snowsea-dev** [comment]
Yes. I used @mapbox/mapbox-sdk 0.12.1

**Comment by snowsea-dev** [comment]
@andrewharvey Sorry. It was another package that using @mapbox/mapbox-gl-native.
