### ISSUE TITLE
CLI utilities

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-sdk-js#42]
I don't particularly care if these are in this package or not. For development and everything else, we need cli utilities.

**Comment by jakepruitt** [comment]
Would it be in separate repos? The [mapbox-data-cli](https://github.com/mapbox/mapbox-data-cli) is pretty much a wrapper around the mapbox-js-sdk.

**Comment by tmcw** [comment]
Yep, let's do this just in mapbox-data-cli.
