### ISSUE TITLE
Mapbox API to provide coordinates (boundaries) to draw the polygon on react native

### ISSUE THREAD

**Issue by codemap01** [mapbox/mapbox-sdk-js#437]
We have a requirement for react native mobile app where we need to select (search) a country or city on the map we need to highlight that city and country and also need an API that provides (Coordinates for draw the polygon) I have explored and we are not able to identify that API to search and provides an array of Coordinates the city and country So Can you suggest any Mapbox API which
h fulfills our requirements because we need this type of API  and 
we have found geocoding API for searching and we still need an API that provides Coordinates for draw the polygon  like this type on the image
I have attached a sample image.
<img width="1283" alt="Mapbox Sample API" src="https://user-images.githubusercontent.com/105269546/167587430-cfa42c78-5973-47c6-b376-4be0f485a84a.png">

**Comment by andrewharvey** [comment]
Please use Mapbox Support for help questions, I can't see anything actionable within this repo so will close.
