### ISSUE TITLE
Got package that insdie node_modules/@mapbox/mapbox-sdk/node_modules/got has old and problematic version

### ISSUE THREAD

**Issue by urlsab** [mapbox/mapbox-sdk-js#448]
I'm using yelp-camp project ( you can check the updated version here : https://github.com/nax3t/YelpCamp-Updates-2022 )
that includes @mapbox/mapbox-sdk package.

The problem is that @mapbox/mapbox-sdk package using old version of Got package (10.7.0) , a version that had a bug that allready fixed by updating the version with a new code (https://github.com/sindresorhus/got/pull/2047/files) 

The cleaner and the simplest solution should be updating Got package inside this repository 

Thanks a lot

**Comment by chriswhong** [comment]
`got` version was bumped up in 1b1a0bd6e5fdfa353d8c898d44bde71007899531
