### ISSUE TITLE
Adding a Static Service

### ISSUE THREAD

**Issue by zeke** [mapbox/mapbox-sdk-js#45]
I'm looking into adding a `static` [service](https://github.com/mapbox/mapbox-sdk-js/tree/master/lib/services) to this library for generating URLs to static map images.

Here's a rough API sketch: 

```js
var MapboxClient = require('mapbox');
var client = new MapboxClient('YOUR_ACCESS_TOKEN');
var url = client.static('mapbox.pencil', ({lon: 123, lat: 456});
```

Is the above feature appropriate for this library?

I can't seem to find a service method that doesn't take a callback. Are there any, or do all the methods hit the network?

**Comment by tmcw** [comment]
I'll sketch out an implementation in a few. For the most part, mapbox-sdk-js has been an abstraction for both URL construction and managing the requests for resources, while this would be for url construction only. That's a simpler task but I suppose it is easier this way than string concat everywhere.

I'm not sure about the [curry/extend](https://gist.github.com/zeke/6572881e4c235d345a1c) thing you posted earlier as a core part of mapbox-sdk-js - that seems like a job for xtend or Object.assign.

**Comment by zeke** [comment]
I'm not attached to that implementation; just want to give the feature a proper home.

**Comment by zeke** [comment]
Pretty impressive that you've managed to keep the minified browser bundle down to just 26K, given everything this module does. :)

**Comment by zeke** [comment]
:clap:
