### ISSUE TITLE
Forward Geocoder: feature.context is sometimes missing but is not option in the TypeScript response type

### ISSUE THREAD

**Issue by zholmes1** [mapbox/mapbox-sdk-js#467]
My app was crashing because I was having it look at the `context` of each feature. In the TypeScript type for GeocodeFeature, `context` looks like it should always be there.

But if you do a geocode for 'waikan', you'll see a result returned (I think it's in Iraq) where context is entirely missing, which is not in sync with the type declaration of the response.

I've already switched away from the SDK to just hitting the Mapbox endpoint with Axios so I can have more control over stuff like this. But I thought I'd let you know.

**Comment by andrewharvey** [comment]
TypeScript isn't directly supported here, would it be an issue with the 3rd party TypeScript support?

**Comment by zholmes1** [comment]
You're correct - my bad, I didn't see that I was using a separate types package! I'm so used to packages just coming pre-loaded with types.
