### ISSUE TITLE
forwardGeocode API improvement on countries

### ISSUE THREAD

**Issue by umrzoq-toshkentov** [mapbox/mapbox-sdk-js#472]
I have a case in `country` property I have set like that.
```
{
  ....
  country: ['US', 'CA']
}
```
while I am doing autocomplete searching 456 broadway, It is returning Canadian states only. Is there any clue to make reorder and prioritise  country. For example I want prioritise US state at first

**Comment by andrewharvey** [comment]
Given the Geocoding API doesn't support this I don't see much the SDK can do.

You could try to set the proximity parameter or make two requests one for US one for CA and do the sorting client side.
