### ISSUE TITLE
Feature pagination on list endpoints

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-sdk-js#50]
We have provisional pagination in place for feature listing API endpoints. We should support these are additional options when running [`.listFeatures()`](https://github.com/mapbox/mapbox-sdk-js/blob/ffd4da71e66e010f650a8f1e1a1ea36052b925dd/lib/services/datasets.js#L207-L250). I would suggest implementing this by changing the function so that it can accept an optional `options` object that may provide the following arguments to the API call:

| Argument | Description |
| --- | --- |
| sortby | The property to use for sorting. `created` and `modified` are currently supported. |
| reverse | Set to `true` to reverse the default sort order of the listing. |
| limit | The *maximum* number of objects to return. This value must be between 1 and 100. The API will attempt to return the requested number of objects, but receiving fewer objects does not necessarily signal the end of the collection. Receiving an empty page of results is the only way to determine when you are at the end of a collection. |
| start | The object id that acts as the cursor for pagination and defines your location in the collection. This argument is exclusive so the object associated with the `id` provided to the `start` argument will not be included in the response. |

```js
Datasets.prototype.listFeatures = function(dataset, options, callback) {
  if (typeof options === 'function') {
    callback = options;
    options = {};
  }

  // ... etc
};
```

cc @isiyu @peterqliu @willwhite

**Comment by willwhite** [comment]
Heads up that `sortby` is not supported for features because features don't have `created` or `modified` properties. It also doesn't support `reverse` because this option doesn't make much sense without `sortby`.
