### ISSUE TITLE
better uri encoding for geocodes

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-sdk-js#59]
I was doing a bit of [forward geocoding](https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md#geocodeforward) and ended up running a string with a line break in it, looked sort of like `100 6th St\nSan Francisco`. It failed with this error message:
 
```
Potentially unhandled rejection [7] Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 0C0WjIdiUNxnFnej1T_D3zhMfAQMXe49QKjAXEdziNroPxHra7E3Zg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/geocoder.js#L56

**Comment by samanpwbb** [comment]
I tried encoding with like `encodeURIComponent(query)` but that failed as well. `query.replace(/(\r\n|\n|\r)/gm,'')` works, but seems like this is a problem that needs to be solved further upstream?

**Comment by tmcw** [comment]
Yeah, potentially upstream in the geocoder cc @ingalls

**Comment by ingalls** [comment]
@tmcw @samanpwbb Definitely seeing this error, from my tests this appears to be a problem with how the query is being encoded in mapbox-sdk-js and not api-geocoder. Since the error is being returned by cloud-front its not even hitting our server.

**Comment by tmcw** [comment]
@samanpwbb can you post the code you're writing to integrate against mapbox-sdk-js? I cannot replicate the issue with the node interface of mapbox-sdk-js.

**Comment by tmcw** [comment]
Upstream bug in cujo https://github.com/cujojs/rest/issues/138 cc @scothis

**Comment by tmcw** [comment]
Fix landed, updating cujo
