### ISSUE TITLE
Dataset support

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-sdk-js#7]
https://github.com/mapbox/mapbox-dataset-sdk and https://github.com/mapbox/mapbox-data-cli both implement interfaces to the upcoming dataset API.

We should integrate the best of both into this library.

**Comment by rclark** [comment]
:+1: would love to pick this up

**Comment by tmcw** [comment]
:+1: it's ready for adoption, the refactor & endpoint customization is pretty much landed and I'm comfortable with this pattern for the rest of the remaining services.
