### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-sdk-js#79]
Upstream tracking ticket: https://github.com/cujojs/rest/issues/137

**Comment by julioahurtado** [comment]
@tmcw Hey I was wondering if this issue has been solved yet or is currently being worked on? I have an idea for a react-native app using your sdk for directions but it wasn't working last time i tried using it.

**Comment by tmcw** [comment]
Rule of thumb is that open tickets are not solved and solved tickets are closed.

**Comment by julioahurtado** [comment]
@tmcw ok sorry about that. I was just unsure because it seems that it's been awhile since there was an update on the issue.

**Comment by simonbdev** [comment]
+1 for RN support

**Comment by tmcw** [comment]
We've updated rest, so the `when` dependency is removed. Tested with React Native and 1.0.0-beta2 is compatible.

![2016-07-20 at 2 23 pm](https://cloud.githubusercontent.com/assets/32314/16997945/9193c1e4-4e85-11e6-9bac-4a2171d75c16.png)

**Comment by GeeWizWow** [comment]
Is react-native still supported?

`error: bundling: UnableToResolveError: Unable to resolve module url from [...]\mapbox\lib\paginator.js`

when `import mapbox from 'mapbox/lib/services/directions';`

**Comment by nitaliano** [comment]
@GeeWizWow just `npm i --save url` and it will work.

**Comment by unicornRainbows** [comment]
@nitaliano is correct, that solves the issue... But since I'm looking for street data for South Africa it does not work since there is no street data for my country of choice... Sad Panda... :(
But love MapBox, and will have to use Google in combination..

**Comment by anastely** [comment]
Any update! i can't use it inside my React native App " directions specific"
