### ISSUE TITLE
Callback failed to be called for insertFeature

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-sdk-js#87]
Yesterday I moved my 24,000 instagram photo points from a local GeoJSON file to a dataset. As the batch request function hadn't been deployed yet I did a serial push via insertFeature. Most of the time it worked fine. There were a few times though when the callback was never called. One time I let it got for a very longtime (at least an hour) so I'm pretty sure the problem is internal to the SDK, but it could be some weird hang up in the api.

/cc @rclark @tmcw

**Comment by tmcw** [comment]
We're going to need a more reproducible or precise bug report for this one to be fixed.

**Comment by mcwhittemore** [comment]
Yea. I just reviewed the code and nothing in the SDK jumps out at me. Maybe something upstream? I'm hoping @rclark  can see how no response might be returned from the server. If he does not, I think we should treat this as a 'needs more detail', close it and then keep our ears open for the same kind of problem from others.

**Comment by rclark** [comment]
Getting to the bottom of this would mean tracking response codes for all 24,000 requests that you're making -- it sounds a lot like a networking-related error where a connection was dropped but the application hung on and waited instead of timing out and retrying after some interval.

**Comment by mcwhittemore** [comment]
Closing this for now.
