### ISSUE TITLE
Enable or document cancelling requests

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-sdk-js#89]
The [rest](https://www.npmjs.com/package/rest) package that mapbox-sdk-js uses internally supports cancelling requests but I don't see a way to call this on `getDirections` or `geocodeForward` in any downstream way. We should document or surface the ability to do this in the api.

cc @scothis @lucaswoj @tmcw

**Comment by scothis** [comment]
Cancelation is tricky (non-standard) in a promise based world. Once the request is initiated, a `request.cancel()` becomes available. You have to have access to the original request object, which the SDK obscures, or it needs to be proxied in somehow.

**Comment by davidtheclark** [comment]
We should be able to return a cancelable Promise along the lines of https://github.com/sindresorhus/p-cancelable

**Comment by davidtheclark** [comment]
The newly published @mapbox/mapbox-sdk has a (hopefully) supports aborting requests.
