### ISSUE TITLE
CORS error when calling updateDataset method

### ISSUE THREAD

**Issue by ramyaragupathy** [mapbox/mapbox-sdk-js#92]
While using `updateDataset` to change dataset information, this function repeatedly failed with the following error message in the [console](http://batpad.github.io/dataset-test/), `Method patch is not allowed by Access-Control-Allow-Methods in preflight response`. However [network log](http://batpad.github.io/dataset-test/) had `PATCH` listed as an allowed method.

```
Access-Control-Allow-Methods:GET,HEAD,PUT,PATCH,POST,DELETE
```

 When the [method name was set to uppercase](https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/datasets.js#L166)  as `PATCH`,  `updateDataset` function worked fine, without any error message.

Here's [the sample code](https://github.com/batpad/dataset-test/blob/gh-pages/src/index.js) to reproduce this.

cc @batpad @tmcw @willwhite

**Comment by davidtheclark** [comment]
I have not noticed this problem with the newly published @mapbox/mapbox-sdk. Please re-open if it returns.
