### ISSUE TITLE
Potentially unhandled rejection[6] error when creating an upload

### ISSUE THREAD

**Issue by aarthykc** [mapbox/mapbox-sdk-js#93]
I used `mapbox-sdk-js` to [upload a geojson](https://github.com/geohacker/shaktiman/blob/master/index.js#L51-L94) created by querying overpass, but it throws the following error 
`potentially unhadled rejection[6] Could not access url (WARNING: non-Error used)` the error is possibly at [this line](https://github.com/geohacker/shaktiman/blob/master/index.js#L72) because I do get a resp object from `s3.putObject`. I tried running a test sample like [this](https://gist.github.com/aarthykc/ead01e45ffb89a714a06da706269f7fd) and it throws the same error. 

Strangely enough, when @geohacker and I tried the same code on Friday it seemed to work back then! 

Are we missing something? 

@geohacker, @batpad, @willwhite, @tmcw

**Comment by davidtheclark** [comment]
Relates to https://github.com/mapbox/mapbox-sdk-js/issues/109.

**Comment by davidtheclark** [comment]
The newly published @mapbox/mapbox-sdk should fix this. Please re-open if it happens again.
